- package.json
- yarn.lock
> YTI-277 yti-common-ui update

- package.json
- yarn.lock
Get new language codes from ytil-common-ui
> YTI-1387 common-ui new version

- Dockerfile
- build.sh
- jest.config.ts
- package.json
- yarn.lock
* can be skipped with argument SKIP_TESTS
* generates coverage in junit.xml for use with jenkins
> run unit tests during container build

- po/en.po
- po/fi.po
- po/sv.po
- po/template.pot
- src/app/components/vocabulary/vocabulary-main.component.ts
Add download link to action menu.
YTI-68
> UI for Excel Export

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/common/components/footer/footer.tsx
- src/layouts/layout.tsx
- src/pages/terminology/[id].tsx
Add static links to accessibility and Data Protection links.
Add dynamic mailto link to feedback link.
YTI-1601
> Footer links

- package.json
- src/common/components/header/header-search.tsx
- src/common/components/terminology-search/terminology-search-results.test.tsx
- src/common/components/terminology-search/terminology-search-results.tsx
- src/common/interfaces/terminology.interface.ts
- src/common/utils/create-getserversideprops.ts
- src/modules/footer/footer.style.tsx
- src/modules/footer/index.tsx
Fix some dependencies and imports
> fix dependencies and imports

- public/locales/en/common.json
- public/locales/fi/common.json
- src/common/components/vocabulary/vocabulary-info.styles.tsx
- src/common/components/vocabulary/vocabulary-info.tsx
Add export/download section to terminology details.
YTI-1608
> Export terminology as excel

- src/common/components/multilingual-definition-list/multilingual-definition-list.styles.tsx
- src/common/components/multilingual-definition-list/multilingual-definition-list.test.tsx
- src/common/components/multilingual-definition-list/multilingual-definition-list.tsx
- src/common/components/vocabulary/vocabulary-info.styles.tsx
- src/common/components/vocabulary/vocabulary-info.tsx
Make reusable component for showing a list of values in multiple languages.
YTI-1607
> Add MultilingualDefinitionList component

- src/common/components/info-dropdown/info-basic.styles.tsx
- src/common/components/info-dropdown/info-basic.tsx
- src/common/components/info-dropdown/info-block.styles.tsx
- src/common/components/info-dropdown/info-expander.styles.tsx
- src/common/components/info-dropdown/info-expander.test.tsx
- src/common/components/info-dropdown/info-expander.tsx
- src/common/components/search-results/search-results.tsx
Original implementation got lost after merge. This commit reimplements the same functionality.
Original PR is #37.
YTI-1608
> Reimplement Excel export UI

- src/common/utils/check-rights.test.ts
During review, I wanted to test check-rights in action, so I wrote some tests for it.
> add unit tests for check-rights

- next.config.js
Add permanent redirection for urls used in old application
> YTI-1651 redirect /concepts -> /terminology

- Dockerfile
- next.config.js
- src/common/components/footer/footer.style.tsx
- src/common/components/footer/footer.tsx
- Read version info from Docker build argument
- Store version.txt file to public directory
- Print version string to footer
> YTI-1638 application version info

- src/common/components/filter/search-input-area.test.tsx
- src/modules/concept/administrative-details-expander.tsx
- src/modules/concept/details-expander.tsx
- src/modules/concept/diagrams-and-sources-expander.tsx
- src/modules/concept/index.tsx
- src/modules/concept/other-details-expander.tsx
> Hide empty expanders in concept page

- src/common/components/impersonate/use-fakeable-users.ts
Fix query parameter in fake login url
> Fix fake login

- package-lock.json
- package.json
Updated suomifi-ui-components from 6.1.0-beta.3 to 6.1.1. Dev and build have been both tested to work as expected.
> Updated suomifi to 6.1.1

- src/common/components/search-results/search-count-tags.tsx
Fixed two bugs with organization and group values.
> Fixed bugs

- src/common/components/search-results/search-count-tags.tsx
- src/common/components/search-results/search-results.tsx
- src/modules/vocabulary/terminology-list-filter.tsx
Fix order of filter chips to match original order. And fix counts of concepts and collections in terminology page.
YTI-1653
> Small fixes to query parameters

- src/common/components/info-dropdown/info-expander.test.tsx
- src/common/components/info-dropdown/info-expander.tsx
- Added information to download button about file format
- Changed Dropdown title to be `h2` instead of default `span`
> Added .xlsx to button & changed expander to header

- src/layouts/layout.styles.tsx
- src/layouts/layout.tsx
- src/modules/smart-header/index.tsx
- src/modules/vocabulary/index.tsx
- src/pages/terminology/[terminologyId].tsx
- Footer and main tags added
- Fixed error in breadcrumbs with screen reader reading 'main content' twice unnecessarily
> Added needed tags and moved breadcrumb from main

- src/common/components/sidebar/sidebar-section.tsx
- src/common/components/sidebar/sidebar.styles.tsx
- src/common/utils/hooks/useGeneratedId.ts
- Sidebar header h1 -> h2
- Sidebar sub-headers h2 -> h3
- Add aria-labelledby to lists
Note. No visual changes in this PR.
YTI-1702
> Fix some accessibility issues from sidebar

- public/locales/en/common.json
- public/locales/fi/common.json
- src/modules/smart-header/logo.tsx
- "Navigate to homepage" information added to header logo for screen readers
> Screen reader support for logo added

- public/locales/en/common.json
- public/locales/fi/common.json
- src/common/components/search-results/search-count-tags.tsx
- src/common/components/search-results/search-results.tsx
- Count of search results is read by screen reader after filter is updated
> Count of results is read correctly

- src/modules/concept/index.tsx
> Add some headings to concept page

- src/modules/collection/collection-sidebar.tsx
Sidebar heading was rendered incorrectly when data is partially
loaded.
YTI-1665
> Fix flashing sidebar heading in collection page

- jest.config.ts
- src/common/utils/create-getserversideprops.ts
- src/common/utils/session.ts
- src/modules/smart-header/index.tsx
- src/pages/terminology/[terminologyId].tsx
- src/tests/terminology/[terminologyId].test.tsx
* add unit test for the SSR method of terminology page
* add query parameters to the common getServerSideProps function
> add tests for terminology SSR

- public/locales/en/admin.json
- public/locales/fi/admin.json
- src/common/components/new-terminology/contact-info.tsx
- src/common/components/new-terminology/information-domains-selector.tsx
- src/common/components/new-terminology/missing-info-alert.tsx
- src/common/components/new-terminology/new-terminology.styles.tsx
- src/common/components/new-terminology/organization-selector.tsx
- src/common/components/new-terminology/prefix.tsx
Fixed bugs related to marking some fields invalid in new terminology form and organization selector
> Fixed noticed bugs

- src/common/components/terminology-components/organization-selector.tsx
Users with only one organization now have their main organization set automatically.
> Fixed a bug with user with only one organization

- src/common/components/terminology-components/type-selector.test.tsx
- src/common/components/terminology-components/type-selector.tsx
- src/common/interfaces/new-terminology.ts
- src/modules/new-terminology/generate-new-terminology.tsx
- src/modules/new-terminology/info-manual.tsx
- src/modules/new-terminology/terminology-initial-state.tsx
- Changed terminologyType to be in use in POST-request
> Enabled terminologyType

- src/common/components/property-value/get-property-value.ts
- src/common/components/title-block/badge-bar.test.tsx
- src/common/components/title-block/badge-bar.tsx
- src/common/components/title-block/index.ts
- src/common/components/title-block/main-title.test.tsx
- src/common/components/title-block/main-title.tsx
- src/common/components/title-block/title-block.styles.tsx
- src/common/components/title/title.tsx
- src/common/utils/hooks/use-title-ref/index.ts
- src/modules/collection/collection.styles.tsx
- src/modules/collection/index.tsx
- src/modules/concept/concept.styles.tsx
- src/modules/concept/index.tsx
- src/modules/new-concept/index.tsx
- src/modules/new-concept/new-concept.styles.tsx
- src/modules/own-information/index.tsx
- src/modules/own-information/own-information.styles.tsx
The page title was implemented multiple times for each page. Refactor it by defining a common component.
No visual changes in this PR.
YTI-1865
> Refactor page title

- public/locales/en/admin.json
- public/locales/fi/admin.json
- src/common/components/axios-base-query/index.tsx
- src/common/components/excel/excel.slice.tsx
- src/common/interfaces/excel.interface.ts
- src/modules/new-terminology/file-upload.test.tsx
- src/modules/new-terminology/file-upload.tsx
- src/modules/new-terminology/index.tsx
- src/modules/new-terminology/info-file.test.tsx
- src/modules/new-terminology/info-file.tsx
- src/modules/new-terminology/new-terminology.styles.tsx
- src/store/index.tsx
- Terminologies can now be added with Excel files
- `axiosBaseQuery` headers can be changed from default (default = `{"Content-Type": "application/json"}`) 
Excel added
Excel being processed
Excel finished
> Yti 1878 excel upload

- src/common/components/counts/counts.slice.tsx
- src/common/components/terminology-search/terminology-search.slice.tsx
- src/pages/index.tsx
- SSR is now enabled in index page
> Yti 1917 front page ssr

- src/pages/index.tsx
Enabled SSR in front page and ensured that cookies work as expected.
> Enable ssr with cookies

- .eslintrc
- package-lock.json
- package.json
- src/common/components/access-request/access-request.test.tsx
- src/common/components/alert/alert.test.tsx
- src/common/components/authentication-panel/desktop-authentication-panel.test.tsx
- src/common/components/breadcrumb/breadcrumb.test.tsx
- src/common/components/click-outside-listener/click-outside-listener.test.tsx
- src/common/components/click-outside-listener/index.tsx
- src/common/components/media-query/media-query-context.tsx
- src/common/components/navigation/desktop-navigation.tsx
- src/common/components/pagination/pagination.test.tsx
- src/common/components/search-results/search-count-tags.test.tsx
- src/common/components/search-results/search-results.test.tsx
- src/common/components/sidebar/sidebar.test.tsx
- src/common/components/term-modal/term-modal.test.tsx
- src/common/components/terminology-components/contact-info.test.tsx
- src/common/components/terminology-components/language-selector.test.tsx
- src/pages/_document.tsx
- src/pages/api/auth/callback.ts
- src/tests/matchMedia.mock.ts
Updated most of npm packages and removed @material-ui/core as it does not support React 18. Unfortunately even latest suomifi-ui-components does not support React 18 yet, so I decided not to try to update all packages.
YTI-1998
> Updated most of npm packages

- src/common/components/pagination/pagination.tsx
Changelog:
Scrolls to top (0,0) when pressing the chevron buttons or the page buttons on the pagination
> YTI-1904: Added scrolling to the top when using pagination

- public/locales/en/admin.json
- public/locales/fi/admin.json
- public/locales/sv/admin.json
- src/modules/edit-concept/concept-terms-block/term-type-modal.tsx
- Show the current term correctly
- Show the current recommended term correctly
- Other small refactorings
YTI-1986
> Small fixes in change term type modal

- src/common/components/relational-information-block/relation-information-block.styles.tsx
Fixed right margins in relation picker modal in the concept page.
YTI-2048
> Fix mobile layout in relation picker of concept

- src/modules/edit-concept/basic-information/other-information.tsx
> Trim concept class

- docs/a11y.md
- src/pages/_app.tsx
The list of elements was not logged with violation by axe's default logger. Improved it by writing a custom logger that just dumps violation objects as is.
Also, add some documentation for the axe.
> feat: improve axe's logging

- README.md
- docs/coding-conventions.md
- docs/commands.md
- project structure
- coding conventions
- commands
- project setup (in Readme)
> docs: add some more documentation

- src/modules/new-terminology/generate-new-terminology.tsx
- src/modules/new-terminology/status-selector.test.tsx
- src/modules/new-terminology/status-selector.tsx
Changelog:
- Add status to payload
- StatusSelector tests
> YTI-2069: Cannot change status on edit terminology

- public/locales/en/admin.json
- public/locales/en/collection.json
- public/locales/fi/admin.json
- public/locales/fi/collection.json
- public/locales/sv/admin.json
- public/locales/sv/collection.json
- src/common/components/save-spinner/index.tsx
- src/common/components/save-spinner/save-spinner.test.tsx
- src/modules/edit-collection/edit-collection.styles.tsx
- src/modules/edit-collection/index.tsx
- src/modules/edit-concept/form-footer.tsx
- src/modules/edit-concept/index.tsx
- src/modules/edit-concept/new-concept.styles.tsx
- src/modules/edit-vocabulary/edit-vocabulary.styles.tsx
- src/modules/edit-vocabulary/index.tsx
- src/modules/new-terminology/new-terminology-modal.tsx
Changelog:
- Save spinner added to all editors
- Some form of test for spinner
> Save spinner added to all forms

- docs/property-value.md
- src/common/components/property-value/get-property-value.ts
- src/common/components/property-value/index.tsx
- src/common/components/property-value/property-value.md
- Add documentation to PropertyValue component and getPropertyValue function.
- Also refactor these a little.
> docs: add documentation to PropertyValue component

- src/modules/collection/index.tsx
- src/modules/concept/index.tsx
- src/modules/vocabulary/index.tsx
Data refetch is not needed anymore if user is logged in
> YTI-2115 Remove duplicate queries

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/common/components/concept/concept.slice.tsx
- src/common/components/pagination/pagination.tsx
- src/common/components/relational-information-block/index.tsx
- src/common/components/relational-information-block/relation-information-block.styles.tsx
- src/common/components/relational-information-block/relational-modal-content.tsx
- src/common/components/relational-information-block/render-concepts.tsx
- src/common/components/relational-information-block/render-expander-content.tsx
- src/common/components/relational-information-block/search.test.tsx
- src/common/components/relational-information-block/search.tsx
- src/common/utils/hooks/use-mount-effect/index.tsx
- Improved relational information modal performance in concept edit page with conditional API calls and pagination
Pagination in modal:
> Yti 2126 modal performance bugfix

- public/locales/en/admin.json
- public/locales/fi/admin.json
- public/locales/sv/admin.json
- src/common/utils/translation-helpers.ts
- src/modules/edit-concept/basic-information/concept-basic-information.tsx
- src/modules/edit-concept/basic-information/status-picker.tsx
- src/modules/edit-concept/generate-concept-test-expected.tsx
- src/modules/edit-concept/generate-concept.test.tsx
- src/modules/edit-concept/generate-concept.tsx
- src/modules/edit-concept/generate-form-data-test-variables.tsx
- src/modules/edit-concept/generate-form-data.tsx
- src/modules/edit-concept/new-concept.types.tsx
- src/modules/edit-concept/validate-form.tsx
- Concept status can now be changed
> Added support for changing concept status

- public/locales/en/admin.json
- public/locales/fi/admin.json
- public/locales/sv/admin.json
- src/common/utils/translation-helpers.ts
Changelog:
- error messages for prefLabel checks
- See https://github.com/VRK-YTI/yti-terminology-api/pull/92
> Add messages for prefLabel checks

- public/locales/en/admin.json
- public/locales/fi/admin.json
- Fixed incorrect translation in edit concept page
> Fixed incorrect translation

- src/common/components/alert/alert.styles.tsx
- src/common/components/error/error.tsx
- Centered alerts in wrapper (2071)
- Added error page variant to 404 error (2098)
> Fixed alerts styling and added 5xx error page

- src/app/components/vocabulary/import-vocabulary-modal.component.ts
Remove csv option from import concepts dialog. New excel import in the new application is used instead
> YTI-2135 remove csv import

- src/modules/edit-concept/generate-concept.tsx
- src/modules/edit-concept/generate-form-data-test-variables.tsx
- src/modules/edit-concept/generate-form-data.tsx
- Removed ConceptLink won't add a Term under `delete` key
- Reverted changes related to FormData generation
> Fixed bugs with modify json generation

- src/common/components/relational-information-block/index.tsx
- src/common/components/relational-information-block/relational-modal-content.tsx
- Fixed relational concept modal bug where chosen concepts would be dropped out with certain workflows
> Tweaked relational modal functionality

- po/en.po
- po/fi.po
- po/sv.po
- src/app/components/vocabulary/vocabularies.component.ts
Added link to new terminology beta
> Added link to the frontpage for trying beta

- terminology-ui/src/modules/concept/index.tsx
- Terms are ordered by language (First Finnish then Swedish and after that other languages) in concept page
> Added sorting by lang

- terminology-ui/src/common/components/terminology-components/language-block.tsx
- terminology-ui/src/common/utils/constants.ts
- terminology-ui/src/modules/edit-collection/index.tsx
- terminology-ui/src/modules/edit-concept/basic-information/concept-basic-information.tsx
Longer text fields (5000) for
- Vocabulary description
- Concept definition
- Collection definition
Linked
https://github.com/VRK-YTI/yti-terminology-api/pull/105
> YTI-2301 - Longer definition for all definition/description fields

- terminology-ui/public/locales/en/admin.json
- terminology-ui/public/locales/fi/admin.json
- terminology-ui/public/locales/sv/admin.json
- terminology-ui/src/common/components/import/excel.error.md
- terminology-ui/src/common/components/import/excel.error.tsx
- terminology-ui/src/common/components/update-with-file-modal/index.tsx
- terminology-ui/src/modules/new-terminology/file-upload.tsx
Changelog:
- Added additional text when possibly uploading excel file to wrong modal
- Changed excel import details into component and add it to update terminology modal
Images can be found in the ticket
> YTI-2231: Added error checking for wrong file

- terminology-ui/public/locales/fi/common.json
- "Keskeneräinen" changed to "Piilotettu" in Finnish translation
> Updated translation

- terminology-ui/public/locales/fi/admin.json
Changelog:
- Changed mistaken translation
> FIX YTI-2331:Fix mistaken text

- terminology-ui/src/modules/edit-collection/concept-picker/expander-concept-content.tsx
- terminology-ui/src/modules/new-terminology/info-manual.tsx
- terminology-ui/src/modules/new-terminology/new-terminology-modal.tsx
- Disabled option for creating a new terminology with a file
> Disabled terminology creation with a file

- common-ui/utils/constants.ts
- terminology-ui/src/common/components/new-concept-modal/new-concept-modal.tsx
- terminology-ui/src/common/components/relational-information-block/search.tsx
- terminology-ui/src/common/components/terminology-components/contact-info.tsx
- terminology-ui/src/common/components/terminology-components/language-block.tsx
- terminology-ui/src/common/components/terminology-components/prefix.tsx
- terminology-ui/src/common/utils/constants.ts
- terminology-ui/src/modules/edit-collection/concept-picker/picker-modal.tsx
- terminology-ui/src/modules/edit-collection/index.tsx
- terminology-ui/src/modules/edit-concept/basic-information/concept-basic-information.tsx
- terminology-ui/src/modules/edit-concept/basic-information/organizational-information.tsx
- terminology-ui/src/modules/edit-concept/basic-information/other-information.tsx
- terminology-ui/src/modules/edit-concept/concept-terms-block/new-term-modal.tsx
- terminology-ui/src/modules/edit-concept/concept-terms-block/term-form.tsx
- terminology-ui/src/modules/edit-concept/list-block/index.tsx
Changelog:
- Change TEXT_AREA_MAX
- use common-ui constants instead of defining twice
> YTI-2353: Change TEXT_AREA_MAX

- terminology-ui/src/common/components/relational-information-block/render-concepts.tsx
- terminology-ui/src/modules/concept/concept.styles.tsx
- terminology-ui/src/modules/concept/details-expander.tsx
- terminology-ui/src/modules/edit-collection/concept-picker/picker-modal.tsx
- terminology-ui/src/modules/edit-collection/index.tsx
- terminology-ui/src/modules/edit-concept/basic-information/concept-basic-information.styles.tsx
- terminology-ui/src/modules/edit-concept/basic-information/concept-basic-information.tsx
- terminology-ui/src/modules/edit-concept/concept-terms-block/concept-terms-block.styles.tsx
- terminology-ui/src/modules/edit-concept/concept-terms-block/index.tsx
- Changed ExpanderGroup parameters to hide unwanted HTML element
- Improved collection save functionality
> Hide unwanted element and tweaked collection form

- terminology-ui/src/modules/concept/utils.tsx
- Fixed concept data retrieval hook
- Targets now correct json keys
> Fixed bug with retrieving data

- terminology-ui/public/locales/sv/common.json
> YTI-2368: Fix translation

- common-ui/components/navigation/desktop-navigation.tsx
- Added correct to urls to navigation bar links
> Fixed links

- terminology-ui/src/modules/edit-collection/index.tsx
- Removed collection description count mismatch error in collection form
> Removed errors about definition count mismatch

- po/en.po
- po/fi.po
- po/sv.po
- src/app/components/vocabulary/vocabularies.component.ts
Change link and text to point to the new terminologies tool
> YTI-2403 change terminologies tool url

- terminology-ui/public/locales/en/collection.json
- terminology-ui/public/locales/en/common.json
- terminology-ui/public/locales/fi/collection.json
- terminology-ui/public/locales/fi/common.json
- terminology-ui/public/locales/sv/collection.json
- terminology-ui/public/locales/sv/common.json
- terminology-ui/src/modules/edit-collection/index.tsx
Changelog:
- Change error message for collection empty form to reflect only requiring name.
- Ran i18n (removed some extra translation in common.json?)
> YTI-2422: Fixed error msg on error message for collection

- datamodel-ui/.env
- datamodel-ui/next.config.js
- datamodel-ui/src/common/components/terminology-search/search-terminology.slice.ts
- datamodel-ui/src/common/interfaces/search-terminology.interface.ts
- datamodel-ui/src/common/interfaces/terminology.interface.ts
- datamodel-ui/src/modules/terminology-modal/index.tsx
- datamodel-ui/src/modules/terminology-modal/terminology-modal.styles.tsx
- datamodel-ui/src/store/api-base-query.ts
- datamodel-ui/src/store/index.tsx
Changelog:
- Search for terminologies
- List them in the modal
- Added terminology api url
> YTI-2483:  get terminology list

- common-ui/components/navigation/mobile-navigation.tsx
- Removed unused code in modal navigation
> Remove unused language picker in modal navigation

- terminology-ui/src/common/components/info-dropdown/info-expander.tsx
- terminology-ui/src/modules/concept/index.tsx
- Fixed a bug with contact link email verification
> Terminology yti 2489 contact bugfix

- datamodel-ui/src/modules/as-file-modal/index.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/pages/api/getModelAsFile.ts
Changelog:
- New as file api page
- Changed as file modal to use new api page
> YTI-2531: as file page

- datamodel-ui/src/modules/association-view/index.tsx
- datamodel-ui/src/modules/attribute-view/index.tsx
- datamodel-ui/src/modules/common-view/index.tsx
Changelog:
- refetch listing when returning from association view
- removed some unused properties
> YTI-2537: refetch assoc listing

- datamodel-ui/src/pages/api/getModelAsFile.ts
See https://github.com/VRK-YTI/yti-datamodel-api/pull/120
> YTI-2497 fix file export path

- terminology-ui/src/modules/new-terminology/info-manual.tsx
add finnish, swedish and english in top of the list
> YTI-2581 fix language order

- datamodel-ui/src/common/components/class/class.slice.tsx
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-view/class-view.tsx
- datamodel-ui/src/modules/delete-modal/index.tsx
Use different endpoints for classes and nodeshapes
Backend changes: https://github.com/VRK-YTI/yti-datamodel-api/pull/129
> YTI-2591 separate endpoints for classes and nodeshapes

- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/modules/association-view/index.tsx
- datamodel-ui/src/modules/attribute-view/index.tsx
- datamodel-ui/src/modules/common-form/index.tsx
- datamodel-ui/src/modules/delete-modal/index.tsx
- datamodel-ui/src/modules/model/index.tsx
Separate endpoints for application profile and library resources. Backend changes https://github.com/VRK-YTI/yti-datamodel-api/pull/136
> YTI-2567 check if application profile

- datamodel-ui/src/common/interfaces/model.interface.ts
- datamodel-ui/src/modules/linked-data-view/index.tsx
- External namespace are rendered in linked data tab
> External namespaces are rendered

- datamodel-ui/next.config.js
- datamodel-ui/src/common/components/code/index.tsx
- datamodel-ui/src/common/interfaces/code-information-domain.ts
- datamodel-ui/src/modules/code-list-modal/index.tsx
- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/store/index.tsx
- Added code list url to docker version of next config
- Removed unused endpoint
- Added pagination to code list modal -> improved modal performance immensely
> Added url to docker build & pagination to codelist

- common-ui/components/form/contact.tsx
- datamodel-ui/public/locales/en/admin.json
- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/public/locales/sv/admin.json
- datamodel-ui/src/common/interfaces/model.interface.ts
- datamodel-ui/src/common/interfaces/new-model.interface.ts
- datamodel-ui/src/common/utils/translation-helpers.ts
- datamodel-ui/src/modules/model-form/generate-payload.tsx
- datamodel-ui/src/modules/model-form/index.tsx
- datamodel-ui/src/modules/model-form/validate-form.tsx
- datamodel-ui/src/modules/model/generate-payload.tsx
- datamodel-ui/src/modules/model/model-edit-view.tsx
- datamodel-ui/src/modules/model/validate-form-update.tsx
- Contact field support and error detection added to model creation and edit
> Added support contact field

- datamodel-ui/next.config.js
- datamodel-ui/src/common/components/code/index.tsx
- datamodel-ui/src/modules/code-list-modal/index.tsx
- Changed code list url to match docker config
- Pagination is reset when filter is updated
> Changed code lists url and fixed modal pagination

- datamodel-ui/src/common/components/code/index.tsx
- datamodel-ui/src/common/interfaces/code-registry.ts
- datamodel-ui/src/modules/association-modal/index.tsx
- datamodel-ui/src/modules/attribute-modal/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/code-list-modal/index.tsx
- datamodel-ui/src/store/api-base-query.ts
- Code list url updated
- Code list modal changed to use code registries instead of information domains
- Language sorting added to code list results
> Fixes to code list modal and API

- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/interfaces/internal-class.interface.ts
- datamodel-ui/src/modules/association-modal/index.tsx
- datamodel-ui/src/modules/attribute-modal/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/index.tsx
- handle external resources in modals
- add default search parameters fo
> YTI-2690 Display external resources

- datamodel-ui/src/modules/class-view/class-view.tsx
- datamodel-ui/src/modules/class-view/resource-info.tsx
Pass `applicationProfile` property to getResource query
> YTI-2591 check model type for fetching attributes and associations

- datamodel-ui/src/modules/documentation/index.tsx
- datamodel-ui/src/modules/linked-data-form/index.tsx
- datamodel-ui/src/modules/model/generate-payload.tsx
- datamodel-ui/src/modules/model/model-edit-view.tsx
- Documentation value is stored correctly when editing data model or data model linked data
> Documentation clears when editing model data fix

- datamodel-ui/src/common/components/datatypes/datatypes.slice.ts
- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/common/interfaces/attribute-form.interface.ts
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/utils.ts
- datamodel-ui/src/store/index.tsx
Changelog:
- Endpoints for attribute and association fixed as they changed in backend
- range can now be set for attribute as well, default being rdfs:Literal. 
- Data types from backend endpoint
> YTI-2665: Added select for attribute datatype

- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/common/utils/translation-helpers.ts
- datamodel-ui/src/modules/resource/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- Correct translations are shown in new resource modal
- Resource data is refetched after editing
- Endpoint related changes copied from https://github.com/VRK-YTI/yti-terminology-ui/pull/441
> Resource bugfix

- datamodel-ui/src/common/components/class/class.slice.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/interfaces/class-form.interface.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/index.tsx
- datamodel-ui/src/modules/class-view/application-profile-flow.tsx
- datamodel-ui/src/modules/class-view/class-view.tsx
- datamodel-ui/src/modules/class-view/utils.ts
- datamodel-ui/src/modules/resource-picker-modal/index.tsx
- Class restrictions should be targeting the correct field
- Fixed identifier (the namespace is shown correctly)
> Tweaked flow functionality

- datamodel-ui/src/common/components/counts/counts.slice.tsx
- datamodel-ui/src/modules/front-page/front-page-filter.tsx
- datamodel-ui/src/pages/index.tsx
use urlstate to update counts based on datamodel filters
> YTI-2586: count query updates based on filters

- common-ui/components/authentication-panel/user-info.tsx
- common-ui/components/filter/checkbox-filter.tsx
- common-ui/components/filter/radio-button-filter.tsx
> Added missing IDs

- datamodel-ui/src/common/components/multi-column-search/index.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/index.tsx
- datamodel-ui/src/modules/resource-picker-modal/index.tsx
- Changing targetClass in application profile classes prompts a modal where users can select desired resources
> Application profile class targetClass flow tweaked

- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/src/common/components/resource/resource-utils-data.ts
- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/common/components/resource/utils.ts
- datamodel-ui/src/common/interfaces/class-form.interface.ts
- datamodel-ui/src/common/interfaces/resource-form.interface.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-view/utils.ts
- datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
- datamodel-ui/src/modules/resource/utils.ts
- Added support for missing options in class and resources forms that use modals to select values
> Missing modal in resources added

- terminology-ui/src/common/components/relational-information-block/index.tsx
- terminology-ui/src/modules/edit-concept/generate-form-data-test-variables.tsx
- terminology-ui/src/modules/edit-concept/generate-form-data.tsx
- Fixed following bugs:
- Selected relational concepts from the same terminology are marked as checked correctly
- Information about terms word class isn't dropped when editing
> Fixed concept form bugs

- datamodel-ui/src/common/components/model-drawer/index.tsx
- datamodel-ui/src/common/utils/hooks/use-set-page.tsx
- datamodel-ui/src/common/utils/hooks/use-set-view.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/model/model-header.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/modules/model/search-view.tsx
- datamodel-ui/src/modules/resource/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
- URL handling improved
- The following are tracked in url
- Opened drawer tab
- Page number in tabs that have this possibility
- (Language - this was previously added)
- Fixed a minor bug with display language change where the url would concat itself incorrectly
> Yti 2674 url improvements

- common-ui/components/form/prefix.tsx
- datamodel-ui/src/common/components/class/class.slice.tsx
- datamodel-ui/src/common/components/class/utils.ts
- datamodel-ui/src/common/components/datatypes/datatypes.slice.ts
- datamodel-ui/src/common/components/fakeable-users/fakeable-users.slice.tsx
- datamodel-ui/src/common/components/model/model.slice.tsx
- datamodel-ui/src/common/components/prefix/prefix.slice.tsx
- datamodel-ui/src/common/components/resource/resource-utils.test.ts
- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/common/components/resource/utils.ts
- datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts
- datamodel-ui/src/common/components/search-models/search-models.slice.tsx
- datamodel-ui/src/common/components/service-categories/service-categories.slice.tsx
- datamodel-ui/src/common/utils/api-utils.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/documentation/index.tsx
- datamodel-ui/src/modules/linked-data-form/index.tsx
- datamodel-ui/src/modules/local-copy-modal/index.tsx
- datamodel-ui/src/modules/model-form/index.tsx
- datamodel-ui/src/modules/model-form/model-form-modal.tsx
- datamodel-ui/src/modules/model/model-edit-view.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/store/api-base-query.test.ts
Changelog: 
- Fixed endpoints
- Had to separate create and modify endpoints in class and resource
- inverted free prefix
> YTI-2695: Fixed endpoint changes from backend

- datamodel-ui/src/common/interfaces/visualization.interface.ts
- datamodel-ui/src/modules/graph/util.test.data.ts
- datamodel-ui/src/modules/graph/utils.ts
Avoid confusion with attribute's and association's sh:path property
https://github.com/VRK-YTI/yti-datamodel-api/pull/162
> YTI-2694 rename path to route

- common-ui/components/form/prefix.tsx
- datamodel-ui/src/modules/model-form/index.tsx
- terminology-ui/src/modules/new-terminology/info-manual.tsx
Changelog:
- no more invertion since its same on datamodel and terminology
- Fix parameter on both datamodel and terminology
> YTI-2695: Fix prefix on terminology and rename a bit

- datamodel-ui/public/locales/en/admin.json
- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/public/locales/sv/admin.json
- datamodel-ui/src/common/components/code/code.slice.tsx
- datamodel-ui/src/common/components/resource/utils.ts
- datamodel-ui/src/common/interfaces/code-registry.ts
- datamodel-ui/src/common/interfaces/resource-form.interface.ts
- datamodel-ui/src/common/interfaces/resource.interface.ts
- datamodel-ui/src/modules/code-list-modal/code-list-modal.styles.tsx
- datamodel-ui/src/modules/code-list-modal/filter-block.tsx
- datamodel-ui/src/modules/code-list-modal/index.tsx
- datamodel-ui/src/modules/code-list-modal/results-and-info-block.tsx
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-form/components/attribute-restrictions.tsx
- datamodel-ui/src/modules/resource/utils.ts
- Code list addition to attribute restriction support added
- Refactored CodeListModal into multiple files
- CodeListModal supports code registry information viewing
> Yti 2684 attr restr codelists

- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/common/components/resource/utils.ts
Changelog:
- Fixed endpoint for property shape
- Requires https://github.com/VRK-YTI/yti-datamodel-api/pull/175 to be merged
> YTI-2709: update endpoint for app profile resource

- datamodel-ui/src/common/components/resource/utils.ts
- datamodel-ui/src/common/interfaces/resource-form.interface.ts
- datamodel-ui/src/common/interfaces/resource.interface.ts
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-form/components/attribute-restrictions.tsx
- datamodel-ui/src/modules/resource/utils.ts
Changelog:
- codelist is now codelists
- is array of codelists instead of 1
> YTI-2731: Changed codelist to work as list

- datamodel-ui/src/common/components/code/code.slice.tsx
- datamodel-ui/src/modules/code-list-modal/index.tsx
- datamodel-ui/src/modules/code-list-modal/results-and-info-block.tsx
- Code list result count fixed by passing a `status` key to API request
> Code list count fixed

- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
Changelog:
- Remove language from payload when not in lang list
> YTI-2689: Remove language from payload when not in lang list

- datamodel-ui/next.config.js
- datamodel-ui/src/common/components/class/class.slice.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/interfaces/simple-resource.interface.ts
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/index.tsx
- datamodel-ui/src/modules/class-view/application-profile-flow.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/class-view/utils.ts
- datamodel-ui/src/modules/resource-picker-modal/index.tsx
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
Changelog:
- Add missing information to resource list data objects
- refactor to correctly have object property be concept instead of sub class
- Changed some places to use the more expansive InternalClassInfo for missing values
> YTI-2728: add missing information to modal

- datamodel-ui/src/common/components/class/utils.ts
- datamodel-ui/src/common/interfaces/class-form.interface.ts
- datamodel-ui/src/common/interfaces/class.interface.ts
- datamodel-ui/src/common/utils/get-value.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/index.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/class-view/utils.ts
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
Changelog:
- Add disjoint with to payload
- Remove getCurie and use curie field instead
> YTI-2730: Add disjoint with class to payload

- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- datamodel-ui/src/modules/graph/nodes/node.styles.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-nodes/convert-to-nodes.test.data.ts
- datamodel-ui/src/modules/graph/utils/convert-to-nodes/convert-to-nodes.test.ts
- datamodel-ui/src/modules/graph/utils/convert-to-nodes/index.ts
- datamodel-ui/src/modules/graph/utils/create-class-node/create-class-node.test.ts
- datamodel-ui/src/modules/graph/utils/create-class-node/index.ts
- Support for adding resource restrictions to application profiles class from nodes tooltip
> Resource restrictions support to graph nodes

- datamodel-ui/public/locales/en/common.json
- datamodel-ui/public/locales/fi/common.json
- datamodel-ui/public/locales/sv/common.json
- datamodel-ui/src/common/interfaces/model-form.interface.tsx
- datamodel-ui/src/common/interfaces/model.interface.ts
- datamodel-ui/src/modules/linked-data-form/index.tsx
- datamodel-ui/src/modules/linked-data-form/linked-item.tsx
- datamodel-ui/src/modules/linked-data-view/index.tsx
- datamodel-ui/src/modules/linked-model/index.tsx
- datamodel-ui/src/modules/model/generate-payload.tsx
Changelog:
- Internal namespace info in linked data tab
> YIT-2998 internal namespace info

- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/concept-block/concept-block.styles.tsx
- datamodel-ui/src/modules/concept-block/index.tsx
- datamodel-ui/src/modules/concept-view/index.tsx
- datamodel-ui/src/modules/resource/utils.ts
Changelog:
- Change to same ConceptView in form as in info view for showing class concept info
- Hide application profile specific "in use in this profile" if not application profile
- Show concept in resource view
> YTI-2758: show concept expander in class form

- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/concept-block/index.tsx
- datamodel-ui/src/modules/resource/resource-form/components/application-profile-top.tsx
- datamodel-ui/src/modules/resource/resource-form/components/association-restrictions.tsx
- datamodel-ui/src/modules/resource/resource-form/components/attribute-restrictions.tsx
- datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/resource-form/resource-form.styles.ts
- Technical names of form fields added
- Style fixed to that input field labels take full available horizontal space
> Added technical names to forms

- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- datamodel-ui/src/modules/graph/nodes/external-node.tsx
- datamodel-ui/src/modules/graph/nodes/node.styles.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-nodes/index.ts
- datamodel-ui/src/modules/graph/utils/create-external-node/index.tsx
- datamodel-ui/src/modules/graph/utils/get-edge-params/index.ts
- Resource information is displayed in application profile graph
- Fixed clipping in edge drawing between nodes
- Improved edge position calculation to support different width class nodes
> Yti 2737 app profile visualization

- datamodel-ui/src/common/utils/has-permission.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/linked-data-view/index.tsx
- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
- Users with DATA_MODEL_EDITOR rights have access to edit the data models
> DATA_MODEL_EDITOR rights checking added

- datamodel-ui/public/locales/en/admin.json
- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/public/locales/sv/admin.json
- datamodel-ui/src/common/components/code/code.slice.tsx
- datamodel-ui/src/common/components/resource/resource-utils-data.ts
- datamodel-ui/src/common/components/resource/utils.ts
- datamodel-ui/src/common/interfaces/resource-form.interface.ts
- datamodel-ui/src/modules/code-list-modal/index.tsx
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/model-form/model-form.styles.tsx
- datamodel-ui/src/modules/resource/resource-form/components/attribute-restrictions.tsx
- datamodel-ui/src/modules/resource/resource-form/components/confirmation-modal.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/utils.ts
Changelog:
- Codelist values can now be used in following fields
- Allowed values
- Default values
- Has value
- If no codelist is selected those fields are text inputs instead
- Shows a modal for confirmation
-  IF deleting a codelist
- If adding codelist when there is data on one of the earlier mentioned fields
> YTI-2984 codelist fields attribute

- datamodel-ui/next.config.js
- datamodel-ui/src/common/components/class/utils.ts
- datamodel-ui/src/common/interfaces/class-form.interface.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/class-view/utils.ts
Changelog:
- Use node instead of utilizesNode (this property does not exist)
- Add properties more selectively depending on if model is applicationprofile or not
> YTI-2680: Change from utilizedNode to node

- datamodel-ui/next.config.js
- datamodel-ui/src/modules/documentation/index.tsx
- Bug with editing buttons not working in new data models documentation tab fixed
- Added support for image rendering and resizing to markdown preview
> Yti 2887 documentation buttons bugfix

- datamodel-ui/package.json
- datamodel-ui/src/modules/documentation/documentation.styles.ts
- datamodel-ui/src/modules/documentation/index.tsx
- package-lock.json
Changelog:
- Update suomifi-icons (suomifi-ui-components still uses older version)
- Use new icons
- Make buttons into secondary
- Update size for buttons
> YTI-2755: update icons in documentation

- common-ui/components/layout/layout.tsx
- common-ui/components/smart-header/index.tsx
- common-ui/components/title-block/badge-bar.tsx
- common-ui/components/title-block/title-block.styles.tsx
- datamodel-ui/src/modules/model/model-header.tsx
- datamodel-ui/src/modules/model/model.styles.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
- UI language selector hidden in model page
- Space between header and graph made smaller
> Lang selector hidden and space between header and content made smaller

- terminology-ui/src/common/components/subscription/subscription.slice.tsx
- Env parameter checking improved to drop values used in development enviroments
> Need for fake login parameter checking improved

- datamodel-ui/src/common/components/multi-column-search/index.tsx
- datamodel-ui/src/common/interfaces/class-form.interface.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-view/application-profile-flow.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/class-view/utils.ts
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- datamodel-ui/src/modules/resource/resource-form/components/association-restrictions.tsx
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
Changelog:
- Show right filters on add attribute/association restriction to class modal
- Proper data added when adding new class restriction
- Reset all class data in initialClassForm
> YTI-3213: Fix search modals

- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
Use UriData object when creating new resource from node shape's view
> YTI-3038 fix uri data handling

- datamodel-ui/src/common/components/model-drawer/model-side-navigation.styles.tsx
- datamodel-ui/src/common/components/model-tools/model-tools.styles.ts
- datamodel-ui/src/modules/documentation/utils.test.ts
- datamodel-ui/src/modules/front-page/index.tsx
- datamodel-ui/src/modules/graph/nodes/node.styles.tsx
- datamodel-ui/src/modules/model/model.styles.tsx
- datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
- Made some CSS changes to fix problems in Safari
- Fixed few CSS syntax errors
- Removed unused imports and variables
> Yti 3107 safari support

- datamodel-ui/src/common/components/class/class.slice.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/remove-reference-modal.tsx
- datamodel-ui/src/modules/class-view/resource-info.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
Changelog:
- Endpoint dynamic for library and app profile
- Adding attribute and association "restrictions" are now possible for library classes
- Also removable
- Move around components to better work with this change
> YTI: Add association and attribute restrictions in class view

- datamodel-ui/src/common/components/counts/counts.slice.tsx
- datamodel-ui/src/common/interfaces/new-model.interface.ts
- datamodel-ui/src/modules/model-form/generate-payload.tsx
Changelog:
- Remove status from new datamodel
- Change default status filters for count query
> YTI-3197: fix count query and remove status from new model

- datamodel-ui/src/modules/create-release-modal/index.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
Was caused by release modal redirecting because create release result was persistent
Changelog:
- Reset release result
- Only check release result if user posted
- Render modals more conditionally
> YTI-3202: Fix freezing on creating release

- terminology-ui/src/modules/concept/index.tsx
- terminology-ui/src/modules/edit-concept/index.tsx
Badge component was removed in PR https://github.com/VRK-YTI/yti-terminology-ui/pull/534
> Use Status component instead of Badge

- datamodel-ui/src/common/components/inline-list/index.tsx
- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/common/components/resource/utils.ts
- datamodel-ui/src/modules/resource/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/utils.ts
- Add constant values for default subPropertyOf and use full uri
- Fixed setting initial reference resource for attribute and association
- Refactor initializing resource form and use more descriptive variable names
> YTI-3404 fix handling subPropertyOf 

- datamodel-ui/src/common/interfaces/simple-resource.interface.ts
- datamodel-ui/src/modules/as-file-modal/index.tsx
- datamodel-ui/src/modules/class-view/resource-info.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/pages/api/getModelAsFile.ts
Add version parameter to fetching resource and exporting model
> YTI-3418: Versioning related fixes

- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/index.tsx
- datamodel-ui/src/modules/class-restriction-modal/utils.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
Changelog:
- Add radiobutton to nodeshape flow
- make util class for mapping to resultType
- use this to simplify resource list mapping everywhere possible since it was same values
- Change status chip to use same chip as everywhere else
- modify resulttype to have appropriate keys, remove unncessary values
> YTI-3310: nodeshape flow radiobutton

- datamodel-ui/src/modules/documentation/index.tsx
- datamodel-ui/src/modules/model/index.tsx
Show documentation for all users. Add hasPermission check to documentation edit button
> YTI-3473 Documentation permissions

- datamodel-ui/src/modules/rename-modal/index.tsx
- Reset resource id if user clicks cancel
- If user performs renaming, new identifier is set as new resource id
> YTI-3328 change logic after renaming

- datamodel-ui/public/locales/en/common.json
- datamodel-ui/public/locales/fi/common.json
- datamodel-ui/public/locales/sv/common.json
- datamodel-ui/src/common/interfaces/resource-form.interface.ts
- datamodel-ui/src/common/interfaces/resource.interface.ts
- datamodel-ui/src/common/utils/translation-helpers.ts
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-form/components/property-toggle.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
Changelog:
- Functional property
- Transitive property
- Reflexive property
> YTI-3192: Add extra options to resources

- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/modules/model/search-view.tsx
- datamodel-ui/src/modules/resource/index.tsx
- Model version is passed to search view
- Unnecessary `if` removed
> Correct version info passed when clicking resource

- datamodel-ui/src/common/interfaces/graph.interface.ts
- datamodel-ui/src/common/utils/has-permission.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/documentation/index.tsx
- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-nodes/index.ts
- datamodel-ui/src/modules/graph/utils/create-class-node/index.ts
- datamodel-ui/src/modules/linked-data-view/index.tsx
- datamodel-ui/src/modules/model-form/index.tsx
- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/modules/resource/index.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
- User organizations are also checked when getting user permissions
> HasPermission improved to check user organizations

- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- Technical name display in visualization fixed with support for detecting external resources via `:` in identifier value
> Fixed technical name visualization

- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/interfaces/internal-class.interface.ts
- datamodel-ui/src/modules/class-restriction-modal/utils.tsx
Changelog:
- Added version number to Model information
> YTI-3482: add version info to resource-list

- datamodel-ui/src/modules/graph/nodes/attribute-node.tsx
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- datamodel-ui/src/modules/graph/utils/create-class-node/create-class-node.test.ts
Add resource information to visualization
**Library attribute**
Name / identifier (data type)
**Library association**
Name / identifier
**Profile attribute**
Name / identifier [cardinality] (data type) [codelist indicator]
**Profile association** 
Name / identifier [cardinality]
Ohher changes
- fixed bug setting view when clicking resource in the graph
> YTI-3309 resource label texts

- datamodel-ui/src/common/interfaces/resource-form.interface.ts
- datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
Use the same default data type in both library and profile
> YTI-3574 fix default range/data type selection

- datamodel-ui/src/common/components/model/model.slice.tsx
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/remove-reference-modal.tsx
- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-nodes/index.ts
- datamodel-ui/src/modules/resource/resource-form/index.tsx
Changelog:
- Don't update graph nodes on every render
- Update graph nodes if something ask for update 
- Done through model.slice with updateVisualization function
- when updating visualization if updateVisualization is true keep old positions
> YTI-3613: update graph nodes if adding resource

- datamodel-ui/src/modules/linked-data-view/index.tsx
Use `getLanguageVersion` function to display namespace's name
> YTI-3372 show namespace's default value

- datamodel-ui/src/common/components/multi-column-search/index.tsx
- datamodel-ui/src/common/interfaces/graph.interface.ts
- datamodel-ui/src/modules/graph/edges/edge.tsx
- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts
- datamodel-ui/src/modules/graph/utils/create-edge/index.tsx
Show association's curie if "Show tehcnical name" is selected in preferences
> YTI-3309 show association's curie in label

- common-ui/.eslintrc
- common-ui/components/block/multilingual-block.styles.tsx
- common-ui/components/block/multilingual-block.tsx
- common-ui/components/file-drop-area/index.tsx
- common-ui/components/form/language-selector.tsx
- common-ui/components/header-search/header-search.styles.tsx
- common-ui/components/header-search/index.tsx
- common-ui/package.json
- datamodel-ui/package.json
- datamodel-ui/src/modules/concept-view/index.tsx
- package-lock.json
- terminology-ui/package.json
- DS updated to beta version to fix few console errors
- Fixed variables that threw console errors
> Updated DS to beta and fixed console errors

- datamodel-ui/src/common/components/resource-error/index.tsx
- datamodel-ui/src/common/utils/has-permission.tsx
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/documentation/index.tsx
- datamodel-ui/src/modules/linked-data-form/index.tsx
- datamodel-ui/src/modules/linked-data-view/index.tsx
- datamodel-ui/src/modules/model/model-edit-view.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/modules/model/search-view.tsx
- datamodel-ui/src/modules/resource/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
- User permission check fixed
- Initial header height values per view
> Fixed permission checking and initial StaticHeader height

- common-ui/components/search-results/result-card.styles.tsx
- common-ui/components/search-results/result-card.tsx
- common-ui/components/search-results/search-count-tags.props.ts
- common-ui/components/status-chip/index.tsx
- common-ui/components/status-chip/status-chip.styles.tsx
- common-ui/components/title/title.styles.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/components/resource-list/resource-list.styles.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/code-list-modal/code-list-modal.styles.tsx
- datamodel-ui/src/modules/code-list-modal/results-and-info-block.tsx
- datamodel-ui/src/modules/model/model-header.tsx
- datamodel-ui/src/modules/model/prior-versions.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
- datamodel-ui/src/modules/terminology-modal/index.tsx
- datamodel-ui/src/modules/terminology-modal/terminology-modal.styles.tsx
- terminology-ui/src/modules/concept/index.tsx
- terminology-ui/src/modules/edit-concept/index.tsx
- terminology-ui/src/modules/edit-vocabulary/index.tsx
- terminology-ui/src/modules/vocabulary/index.tsx
* use one base component for StatusChip
* change colors based on new design
> refactor status chip structure and colors

- datamodel-ui/src/modules/graph/nodes/node.styles.tsx
- Max width set to class nodes in graph
- If resource name exceeds the maximum width add dots at the end of the text
> Long resource names style fixed

- datamodel-ui/src/modules/model/model-header.tsx
- Content language picker style bug fixed on initial load
> Fixed content language picker initial style

- datamodel-ui/src/pages/model/[...slug].tsx
- If an anonymous user or unauthenticated user tries to access a work version of data model page directly they are redirected back to front page
> User permission checked for working version of data models

- datamodel-ui/src/common/components/resource/resource.slice.tsx
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/resource/resource-form/components/association-restrictions.tsx
- datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
- Change selectResource to return typed resource instead of any type
- hide resources if they are already added
> YTI-3394: hide added resources from modals

- datamodel-ui/src/common/components/model-tools/index.tsx
- datamodel-ui/src/modules/model/index.tsx
- Visualization position data saving allowed in versioned data models
> Visualization positions save allowed in versioned

- terminology-ui/public/locales/en/admin.json
- terminology-ui/public/locales/fi/admin.json
- terminology-ui/public/locales/sv/admin.json
- terminology-ui/src/common/components/access-request/access-request.styles.tsx
- terminology-ui/src/common/components/expander-title/index.tsx
- terminology-ui/src/common/components/relational-information-block/render-concepts.tsx
- terminology-ui/src/common/components/subscription/remove-subscription.tsx
- terminology-ui/src/common/components/terminology-components/contact-info.tsx
- terminology-ui/src/common/components/terminology-components/organization-selector.tsx
- terminology-ui/src/modules/edit-collection/concept-picker/picker-modal.tsx
- terminology-ui/src/modules/new-terminology/info-manual.tsx
- terminology-ui/src/modules/new-terminology/new-terminology-modal.tsx
- Fixed terminology build after breaking changes caused by the newest version of Design System
> Fixed terminology build

- datamodel-ui/src/common/components/resource/utils.ts
Changelog:
- Remove some properties that do not belong in the payload
- delete subject if concept field is empty
> YTI-3405: remove unnecessary value on payload

- datamodel-ui/public/locales/en/admin.json
- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/public/locales/sv/admin.json
- datamodel-ui/src/common/components/model-drawer/index.tsx
- datamodel-ui/src/modules/linked-data-form/index.tsx
- datamodel-ui/src/modules/linked-data-form/linked-item.tsx
- Possible backend and missing values errors are displayed in linked data form
> Linked data errors display support

- datamodel-ui/src/common/components/visualization/visualization.slice.tsx
- datamodel-ui/src/modules/graph/index.tsx
- Added support for versioned visualization position saving
> Versioned visualization data PUT support added

- datamodel-ui/src/common/components/inline-list/index.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/components/uri-info/index.tsx
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/concept-view/index.tsx
- datamodel-ui/src/modules/linked-data-view/index.tsx
Changelog:
**getEnvParam**
- Make uri required value instead of checking for null
- check iri.suomi.fi as alternative
- add beta address
- add v1 addresses
**links**
- add to getEnvParam to all possible uri.suomi.fi links
> add env params to places where needed

- datamodel-ui/public/locales/en/admin.json
- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/public/locales/sv/admin.json
- datamodel-ui/src/common/components/multi-column-search/index.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/components/resource-list/resource-list.styles.tsx
- datamodel-ui/src/modules/linked-model/external-form.tsx
- datamodel-ui/src/modules/linked-model/index.tsx
- datamodel-ui/src/modules/linked-model/list-form.tsx
- Adding linked data model modal reworked to use `<MultiColumnSearch />` and related components
> Linked data models modal reworked

- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- Fixed a bug with displaying class resource by type
> Displaying by resource type fixed

- datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts
- datamodel-ui/src/modules/graph/utils/visualization-test-data/index.ts
- Fixed an error with linked attributes edge identifier
> Fixed incorrect identifier setup

- datamodel-ui/src/pages/api/getModelAsFile.ts
Add jsessionid and shibboleth cookies to export request.
> YTI-3683 add cookies to export request

- datamodel-ui/public/locales/en/admin.json
- datamodel-ui/public/locales/en/common.json
- datamodel-ui/public/locales/fi/admin.json
- datamodel-ui/public/locales/fi/common.json
- datamodel-ui/public/locales/sv/admin.json
- datamodel-ui/public/locales/sv/common.json
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/remove-reference-modal.tsx
- datamodel-ui/src/modules/class-view/resource-info.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/graph/nodes/class-node.tsx
- datamodel-ui/src/modules/graph/nodes/node.styles.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
Changelog:
- Change tooltip to actionmenu
- i81n reordered some translations
> YTI-3675: change tooltip to actionmenu

- common-ui/components/breadcrumb/breadcrumb.styles.tsx
- common-ui/components/title-block/title-block.styles.tsx
- terminology-ui/src/modules/concept/concept.styles.tsx
- Fixed layout breaking with long strings
> Fixed layout breaking

- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts
- Fixed wrong id and type when clicking edge
> Fixed bug with incorrect identifier and type props

- datamodel-ui/src/common/interfaces/simple-resource.interface.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-view/application-profile-flow.tsx
- datamodel-ui/src/modules/resource-picker-modal/index.tsx
- datamodel-ui/src/modules/resource-picker-modal/util.tsx
Changelog:
- make util function for converting attribute and assocation
- add version parameter for application profile flow
> YTI-3679: add getting version to application profile flow

- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/utils/create-class-node/index.ts
- datamodel-ui/src/modules/graph/utils/generate-positions-payload/index.ts
- datamodel-ui/src/modules/graph/utils/get-between-nodes/index.tsx
- datamodel-ui/src/modules/graph/utils/get-connected-elements/index.ts
- datamodel-ui/src/modules/graph/utils/get-edge-params/index.ts
- datamodel-ui/src/modules/graph/utils/get-start-node/index.tsx
- datamodel-ui/src/modules/graph/utils/graph-utils/index.tsx
- Cleaned graph related functions a bit and added some descriptive texts
> Graph refactor and cleanup

- datamodel-ui/src/modules/class-view/resource-info.tsx
- datamodel-ui/src/modules/common-view-content/index.tsx
Show association target in the class instead of rdfs:range
> YTI-3689 fix displaying associations target

- datamodel-ui/src/modules/graph/nodes/class-node.tsx
Hide add attribute/association menu from class nodes in the graph if not in draft version
> YTI-3707 check if draft version

- datamodel-ui/src/modules/graph/utils/get-edge-params/index.ts
- Reworked and improved readability of `getEdgeParams()`
> Improved getEdgeParams

- datamodel-ui/src/modules/rename-modal/index.tsx
- Bug with incorrect default identifier value in renaming modal fixed
> Fixed identifier change init value bug

- datamodel-ui/src/modules/model/model-info-view.tsx
- Fixed version checking when creating a new release. Creating a new version is disabled when moving into a newly released data model for the first time
> Fixed version information update

- datamodel-ui/src/modules/graph/nodes/node.styles.tsx
- Fixed long text styles
- Button stays visible
- Excess text is replaced with three dots
> Fixed class name text style

- common-ui/components/status-chip/status-chip.styles.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
- `StatusChip` text changed to be capitalized instead of uppercase
- Correct chip put to use in Class and Resource information page
> StatusChips text style fixed

- datamodel-ui/src/common/utils/create-getserversideprops.ts
- terminology-ui/src/common/utils/create-getserversideprops.ts
- Anonymous users are redirected to front page instead of an error page
> Anonymous user redirect updated

- common-ui/components/filter/language-filter.tsx
- common-ui/components/filter/organization-filter.tsx
- Changed `SingleSelect`s used in Filter to uncontrolled state to fix a bug where removed value would linger in the text field
> Fixed filter SingleSelect state bug

- common-ui/components/navigation/desktop-navigation.tsx
- Locale added to links for interoperability tools in navigation
> Added locale to nagivation links

- datamodel-ui/src/common/components/resource-list/resource-list.styles.tsx
- Increased first column minimum width to ensure that resource information doesn't break too early
> Increased first column min-width

- datamodel-ui/src/modules/model/index.tsx
- Fixed version checking after creating a release
> Fixed version checking

- common-ui/components/navigation/desktop-navigation.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- Versioned data model meta information can be updated (YTI-3721)
- Fixed Koodistot link to be without localization (YTI-3700)
> Fixed minor bugs

- common-ui/components/drawer/static-header.tsx
- Enlarged blur field a bit and tweaked transparency and white colour values
> Increased blur size and tweaked colours

- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/modules/code-list-modal/filter-block.tsx
- datamodel-ui/src/modules/code-list-modal/results-and-info-block.tsx
- datamodel-ui/src/modules/concept-block/index.tsx
- datamodel-ui/src/modules/terminology-modal/index.tsx
- Possibilities to use Space and Enter key in item selections improved
> Added Enter and Space support for uniform functionality

- datamodel-ui/src/modules/graph/index.tsx
- datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts
- A loop is added to self targeting associations by default
> Self targeting associations are setup correctly

- common-ui/README.md
- common-ui/components/layout/layout.tsx
- common-ui/components/locale-chooser/desktop-locale-chooser.tsx
- common-ui/components/locale-chooser/mobile-locale-chooser.tsx
- common-ui/components/locale-chooser/use-locales.ts
- common-ui/components/navigation/mobile-navigation.tsx
- common-ui/components/smart-header/index.tsx
- datamodel-ui/README.md
- datamodel-ui/next-i18next.config.js
- datamodel-ui/src/common/components/layout/index.tsx
- datamodel-ui/src/modules/documentation/documentation.styles.ts
- datamodel-ui/src/modules/graph/utils/get-edge-params/index.ts
- docs/a11y.md
- docs/authentication.md
- docs/coding-conventions.md
- docs/commands.md
- docs/confirm-before-leaving-the-page.md
- docs/matomo.md
- docs/property-value.md
- docs/troubleshooting.md
- terminology-ui/README.md
- Added corrections to READMEs
- Fixed edge offset calculation
- Disabled Swedish from Data models available locales
- Tweaked styles in Documentation page
> Improved READMEs, tweaked documentation style and disabled sv support

- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/resource-info.tsx
Sort attribute and association lists by label
> YTI-3841 sort resources by label

- terminology-ui/src/common/components/info-dropdown/info-expander.tsx
- terminology-ui/src/modules/collection/index.tsx
- terminology-ui/src/modules/concept/index.tsx
- Move concept's and collection's URI below title
- Move terminology's URI below description
> YTI-3822 Move uri

- terminology-ui/src/modules/edit-collection/concept-picker/picker-modal.tsx
The lack of pagination only allowed seeing the first 100 terms. Pagination is now added in the same way as it's done in adding related terms.
> add pagination to adding terms to collection

- common-ui/components/search-results/result-card.styles.tsx
- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
Removed some style definitions, which broke the view in Safari.
> YTI-3848 Safari style issues

- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
Revert fullscreen check from PR https://github.com/VRK-YTI/yti-ui/pull/682
> YTI-3848 revert datamodel page style fix

- datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts
- also check hidden node's origin when displaying association's label
- small adjustments for creating nodes with reference to the same class
> YTI-3823 Fix association labels in the graph

- datamodel-ui/src/common/components/multi-column-search/index.tsx
- datamodel-ui/src/modules/class-modal/index.tsx
- datamodel-ui/src/modules/class-view/resource-modal.tsx
- datamodel-ui/src/modules/resource/resource-modal/index.tsx
Paging was broken in resource selection modals. To fix this:
* correctly set totalHitCount from API response
* remove multiplier from handlePageChange in MultiColumnSearch
> fix paging in resource modals

- datamodel-ui/src/modules/model/model-info-view.tsx
Hide subscribe model action until backend functionality is ready
> YTI-3885 hide subscription button

- datamodel-ui/src/modules/linked-model/list-form.tsx
See backend changes for querying resources https://github.com/VRK-YTI/yti-datamodel-api/pull/283
> YTI-3874 include draft models to the search results

- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-info/index.tsx
Pass organization ids to common resource view component
> YTI-3956 fix permission error displaying editorial note

- datamodel-ui/public/locales/en/common.json
- datamodel-ui/public/locales/fi/common.json
- datamodel-ui/public/locales/sv/common.json
- datamodel-ui/src/common/components/class/utils.ts
- datamodel-ui/src/common/interfaces/class-form.interface.ts
- datamodel-ui/src/common/interfaces/class.interface.ts
- datamodel-ui/src/modules/class-form/index.tsx
- datamodel-ui/src/modules/class-view/class-info.tsx
- datamodel-ui/src/modules/class-view/utils.ts
Add single text field for API path to the profile class form. Changes to backend in this [PR](https://github.com/VRK-YTI/yti-ui/pull/701)
> YTI-3940 Add api path for node shapes

- datamodel-ui/src/common/components/model/model.slice.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
Enable subscribing notifications from the UI
> YTI-3623 Notifications

- datamodel-ui/src/modules/model-form/index.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
Show child organizations in edit view and hide them in public view.
> YTI-4087 Handle child organizations

- datamodel-ui/src/common/components/model/model.slice.tsx
- datamodel-ui/src/common/utils/hooks/use-set-view.tsx
- datamodel-ui/src/modules/documentation/index.tsx
- datamodel-ui/src/modules/front-page/index.tsx
- datamodel-ui/src/modules/linked-data-view/index.tsx
- datamodel-ui/src/modules/model/index.tsx
- datamodel-ui/src/modules/model/model-info-view.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
- Redirect URLs without version parameter to the latest version of the model
- Add separate parameter for viewing draft version
- Add missing parameters to server side requests
> YTI-4151 redirect latest version

- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-form/index.tsx
Functional property option is available only for attributes.
> YTI-4090 Remove functional property from associations

- common-ui/utils/constants.ts
- datamodel-ui/src/common/components/multi-column-search/index.tsx
- datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts
- datamodel-ui/src/common/components/search-models/search-models.slice.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/front-page/index.tsx
- datamodel-ui/src/modules/linked-model/list-form.tsx
- datamodel-ui/src/modules/model/search-view.tsx
- datamodel-ui/src/modules/resource/index.tsx
- datamodel-ui/src/pages/model/[...slug].tsx
- Starting index is not calculated in frontend, but only page number is sent to backend
- Add constants for default start page and two page sizes (20 or 50)
> YTI-4111 Move pagination logic to backend

- datamodel-ui/src/common/components/model-tools/index.tsx
- datamodel-ui/src/common/components/model-tools/useCenterNode.ts
- datamodel-ui/src/common/components/model/model.slice.tsx
- datamodel-ui/src/modules/class-view/index.tsx
- datamodel-ui/src/modules/graph/index.tsx
- Create hook for centering selected node
- New class will be centered after creation
- Add a few zoom levels and change fitView options so larger graphs fit better to the screen
> YTI-3853 focus class in visualization after creation

- datamodel-ui/public/locales/en/common.json
- datamodel-ui/public/locales/fi/common.json
- datamodel-ui/public/locales/sv/common.json
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/resource/resource-form/components/attribute-restrictions.tsx
Show restrictions
- max count
- min count 
- code lists
Other restrictions moved to expander
> YTI-3941 Move some restrictions to expander

- common-ui/components/layout/layout.styles.tsx
- common-ui/components/layout/layout.tsx
- datamodel-ui/src/modules/model/index.tsx
Fix layout issues in model graph view with Safari
> YTI-3848 add potential fix for layout problem with safari

- terminology-ui/src/modules/terminology-search/index.tsx
The old application is no longer in use after migrating to Fuseki data
> YTI-4244 remove link to old application

- datamodel-ui/src/common/components/datatypes/datatypes.slice.ts
- datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
See backend changes https://github.com/VRK-YTI/yti-datamodel-api/pull/322
> YTI-4221 add more datatypes for application profile

- terminology-ui/public/locales/en/admin.json
- terminology-ui/public/locales/fi/admin.json
- terminology-ui/public/locales/sv/admin.json
- terminology-ui/src/common/components/import/excel.error.tsx
- terminology-ui/src/common/components/terminology-search/terminology-search.slice.tsx
- terminology-ui/src/common/utils/translation-helpers.ts
- terminology-ui/src/modules/new-terminology/file-upload.tsx
Remove unused error keys and fixed handling error details.
Backend PR: https://github.com/VRK-YTI/yti-terminology-api/pull/155
Other fix: change search parameter prefLang to sortLang
> YTI-4056 Excel import error handling

- terminology-ui/src/common/components/access-request/access-request-modal.tsx
- terminology-ui/src/common/components/info-dropdown/info-expander.tsx
- terminology-ui/src/common/interfaces/counts.interface.ts
- terminology-ui/src/modules/terminology-search/search-page-filter.tsx
- terminology-ui/src/modules/vocabulary/terminology-list-filter.tsx
- fix user requests api url (request -> requests)
- enable html in terminology's description
- fix count data structure and add sorting to language filter list
> YTI-4103 Fixes for counts and requests

- terminology-ui/src/pages/sitemap.xml.tsx
- terminology-ui/src/pages/terminology/[terminologyId].tsx
- terminology-ui/src/pages/terminology/[terminologyId]/concept/[conceptId].tsx
- Get page titles from new terminology data
- Add host header to the sitemap request
> YTI-4256 fix page titles and sitemap

- common-ui/components/sanitized-text-content/index.tsx
- common-ui/utils/link-utils.ts
- datamodel-ui/src/common/components/inline-list/index.tsx
- datamodel-ui/src/common/components/resource-list/index.tsx
- datamodel-ui/src/common/components/uri-info/index.tsx
- datamodel-ui/src/common/components/uri-list/index.tsx
- datamodel-ui/src/modules/common-view-content/index.tsx
- datamodel-ui/src/modules/concept-view/index.tsx
- datamodel-ui/src/modules/linked-data-view/index.tsx
Move `getEnvParameter` method to common-ui and use that functionality to determine env parameter for uri/iri.suomi.fi links.
> YTI-4227 fix env parameter in concept's definition

- terminology-ui/src/common/components/modify-statuses/modify-statuses.slice.tsx
- terminology-ui/src/common/components/status-mass-edit/index.tsx
Old UI implementation but change to v2 api. Backend changes https://github.com/VRK-YTI/yti-terminology-api/pull/162
> YTI-4125 modify statuses v2 api

- datamodel-ui/src/modules/class-view/resource-info.tsx
Pass organization ids to the component to check permissions for deleting attribute's codelist.
> YTI-4273 Fix codelist remove permissions

- terminology-ui/src/modules/edit-concept/index.tsx
Create term placeholder only if value is specified
> YTI-4304 Create recommended term's

- common-ui/components/form/language-selector.tsx
This should match the current backend limit.
> increase max length for documentation textarea
