VRK-YTI/yti-ui

src/app/utils/validator.ts
Modify new line regular expression to accept also \r\n. Previous check didn't work if the content was copied from MS Word
=> YTI-1373 Fix semantic text validation

src/common/components/filter/filter.styles.tsx, src/common/components/info-dropdown/info-basic.styles.tsx, src/common/components/info-dropdown/info-basic.tsx, src/common/components/info-dropdown/info-block.styles.tsx, src/common/components/info-dropdown/info-block.tsx, src/common/components/info-dropdown/info-expander.tsx, src/common/components/multilingual-definition-list/multilingual-definition-list.styles.tsx, src/common/components/property-value/get-property-value.ts, src/common/components/property-value/index.tsx, src/common/components/property-value/property-value.test.tsx, src/common/utils/format-iso-date.ts, src/modules/concept/concept-sidebar.tsx, src/modules/vocabulary/index.tsx
Refactor terminology page so that it uses MultilingualDefinitionList and PropertyValue components where possible.
=> YTI-1067 Use MultilingualDefinitionList in terminology page

next-env.d.ts, public/locales/en/common.json, public/locales/fi/common.json, src/common/components/filter/checkbox-area.tsx, src/common/components/filter/dropdown-area.tsx, src/common/components/filter/filter-props.tsx, src/common/components/filter/filter.styles.tsx, src/common/components/filter/filter.tsx, src/common/components/filter/radio-button-area.tsx, src/common/components/filter/search-input-area.tsx, src/common/components/impersonate/mobile-impersonate-wrapper.tsx, src/common/components/search-results/search-results.styles.tsx, src/common/components/search-results/search-results.tsx, src/modules/terminology-search/index.tsx, src/modules/terminology-search/terminology-search.styles.tsx, src/modules/vocabulary/index.tsx, styles/globals.scss
Added mobile version of filter.
- If used in mobile view, the filter can be opened from a button to a modal which takes the whole screen. The functionality of filter hasn't been altered.
- Checkboxes and radio buttons size is larger in mobile view.
- Close button appears in header when in mobile view. 
Filter is initially hidden in mobile which can be opened from a new button.
Filter open in search page.
Filter open in a terminology page.
=> Yti 1615 filter mobile version

src/common/components/axios-base-query/index.tsx, src/common/components/collection/collection-slice.tsx, src/common/components/concept/concept-slice.tsx, src/common/components/terminology-search/terminology-search-slice.tsx, src/common/components/vocabulary/vocabulary-slice.tsx
Warnings about using fetch with SSR pages have previously emerged when running unit tests. Therefore Redux toolkit's baseQueryFn has been replaced with an Axios component.
- Added new component to replace baseQueryFn that uses Axios
- Replaces all createApi() to use the new component instead of baseQueryFn
=> Switched from Fetch to Axios

src/app/components/common/meta-information.component.ts
Check if modifier or creator user name exists in the response. Backend doesn't return names anymore if user is not part of any vocabulary's contributor organization.
Related to https://github.com/VRK-YTI/yti-terminology-api/pull/34
=> YTI-1624 check created- and modified by

Dockerfile, package.json, src/common/components/formatted-date/format.test.ts, src/common/components/formatted-date/formatted-date.test.tsx
Day.js uses system time zone automatically so it causes problems
when developers' machines are running in different time zone than CI.
=> Fix time zone problem from tests

public/locales/en/common.json, public/locales/fi/common.json, src/common/components/filter/filter.tsx, src/common/components/skip-link/skip-link.styles.tsx, src/common/components/skip-link/skip-link.test.tsx, src/common/components/skip-link/skip-link.tsx, src/layouts/error-layout.tsx, src/layouts/layout.tsx, src/modules/collection/index.tsx, src/modules/concept/index.tsx, src/modules/terminology-search/index.tsx, src/modules/vocabulary/index.tsx
Add two skip links:
- "Go to main content" link to the beginning of every page.
- "Go to search results" link to the beginning of filter pane in terminology list and terminology details pages.
Error pages are only exceptions without skip links. That's because translations are not available there and they are pretty simple pages so they don't even need any skip links.
YTI-1691
=> Skip links

public/locales/en/common.json, public/locales/fi/common.json, src/common/components/pagination/pagination-props.tsx, src/common/components/pagination/pagination.styles.tsx, src/common/components/pagination/pagination.tsx, src/common/components/search-results/search-count-tags.tsx, src/common/components/title/title.slice.tsx, src/common/components/title/title.tsx, src/modules/collection/index.tsx, src/modules/concept/index.tsx, src/pages/_app.tsx, src/store/index.tsx
- Reworked pagination to use `Button` instead of `div`.
- Added `VisuallyHidden` component to update user about which page has been moved to.
- Page focus is set to be page title (excluding front page) on load.
=> Yti 1692 accessibility page change

src/common/components/sanitized-text-content/index.tsx, src/common/components/sanitized-text-content/sanitized-text-content.test.tsx
- Added two missing internal link data types and fixed unit tests
=> Added 'broader' and 'related' as internal links

public/locales/en/common.json, public/locales/fi/common.json, src/common/components/footer/footer.tsx, src/common/components/title/title.tsx, src/modules/footer/index.tsx
- Footer logo and version info are hidden from screen readers
- External links describe to screen readers which service the user is opening the link to
- Email receiver information is added to screen reader
- Fixed a bug with `<Title>` state
=> Yti 1704 improving footer

src/common/components/search-results/search-results.styles.tsx, src/common/components/search-results/search-results.tsx
- Convert search results to list
- Use h2 as a card heading instead of h3
- Use p and div instead of span so that screen reader will not read
everything by once.
- Add organization name after card heading for screen readers
Note. No visual changes in this PR.
YTI-1695
=> Fix some accessibility issues from search results

src/common/components/sidebar/sidebar.styles.tsx, src/common/components/sidebar/sidebar.tsx, src/modules/collection/collection-sidebar.tsx, src/modules/concept/concept-sidebar.tsx
When sidebar is empty, it is rendered as an empty aside box in
desktop mode. In mobile, it is still hidden.
As it is only empty aside box, it is hidden from screen readers.
Empty sidebar in desktop mode:
YTI-1665
=> Sidebar empty state

src/common/components/filter/checkbox-filter.tsx, src/common/components/filter/filter.styles.tsx, src/common/components/filter/filter.tsx, src/common/components/filter/keyword-filter.tsx, src/common/components/info-dropdown/info-expander.tsx, src/common/components/separator/index.tsx, src/common/components/separator/separator.styles.tsx, src/modules/concept/index.tsx, src/modules/terminology-search/index.tsx, src/modules/terminology-search/terminology-search.styles.tsx, src/modules/vocabulary/index.tsx, src/modules/vocabulary/vocabulary.styles.tsx
- Make filter panel act as a region
- Filter header is h2
- Move filter before search results
- Group checkboxes into fieldset with legend
- Hide separators from screen readers
Note. No visual changes in this PR.
YTI-1690
=> Fix some accessibility issues from filter panel

public/locales/en/collection.json, public/locales/en/common.json, public/locales/fi/collection.json, public/locales/fi/common.json, src/common/components/block/block.styles.tsx, src/common/components/block/concept-list-block.tsx, src/common/components/info-dropdown/info-expander.tsx, src/modules/collection/index.tsx, src/modules/concept/index.tsx
- Remove broader concepts section from collection page.
- Hide heading of collection members if the list is empty.
- Convert some detail headings into actual h2 and h3 elements.
- Add additional technical information heading for screen readers
in all pages.
YTI-1714, YTI-1703, YTI-1705, YTI-1725
=> Fix some a11y issues from multiple pages

src/common/components/block/concept-list-block.tsx, src/common/components/page-title/index.tsx, src/common/components/page-title/title.tsx, src/common/components/title/title.tsx, src/common/utils/get-property.test.ts, src/common/utils/get-property.ts, src/layouts/layout.tsx, src/modules/collection/index.tsx, src/modules/concept/index.tsx, src/modules/vocabulary/index.tsx, src/pages/404.tsx, src/pages/500.tsx, src/pages/index.tsx, src/pages/search.tsx, src/pages/terminology/[terminologyId].tsx, src/pages/terminology/[terminologyId]/collection/[collectionId].tsx, src/pages/terminology/[terminologyId]/concept/[conceptId].tsx
In some cases, page title was not translated correctly.
For example, in concept page the title should contain prefLabel
from prefLabelXl term. Terms are language spesific so one term
contains prefLabel in one language. Thus is is not good enough to
get prefLabel from the first prefLabelXl but instead from all of
them.
In addition, refactored rendering of page title into single
component. Testing it was very hard (because of how next/head
works) so no tests for it in this commit.
YTI-1708
=> Fix some i18n issues from page title

src/common/components/term-modal/index.tsx, src/common/components/term-modal/term-modal.style.tsx
- Fixed styling for Button and Chip. Chip was changed from suomifi-components Chip to span
Font style is now same with other similar components:
=> Fixed modal button and chip styles

src/common/components/alert/alert.slice.tsx, src/common/utils/create-getserversideprops.ts, src/common/utils/session.ts, src/pages/terminology/[terminologyId]/collection/[collectionId].tsx, src/pages/terminology/[terminologyId]/concept/[conceptId].tsx
The url params are available for `getServerSideProps`, but the common implementation didn't include them.
https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter
Additionally `getServerSideProps` will now throw an error if the parameters are missing, instead of just setting them to empty strings.
=> Yti 1712 read url parts from getServerSideProps context

src/modules/terminology-search/index.tsx
`previousAlerts` got added as an dependency for some reason and caused an infinite loop in terminology-search -module.
=> Removed looping dependency from useEffect

src/common/components/counts/counts-slice.tsx
`vocabularies=true` parameter added to counts request for https://github.com/VRK-YTI/yti-terminology-api/pull/43.
This can be merged before api PR is merged (doesn't brake functionality, tested locally).
=> Added param for getting only terminology counts

package-lock.json, package.json, src/common/components/subscription/remove-subscription.tsx, src/common/components/suomifi-7-tweaks/icon-button.tsx, src/common/components/suomifi-7-tweaks/icon.styles.tsx, src/common/components/suomifi-7-tweaks/icon.tsx
Extract some files from suomifi-ui-components v7.0.0-beta.0 and
tweak them to allow us to use alertOff icon without updating the
whole library.
Note: Pretty much revert this commit after suomifi-ui-components
is updated to v7.
=> Hack: Use alertOff icon without updating suomifi-ui-components

.github/workflows/ci.yml, .prettierignore
This is a duplicate CI process only meant to aid with pull requests on github.
The workflow is essentially the same as in #30, where at the time we decided to not add a secondary CI process.
=> add github actions workflow

.env, docs/matomo.md, src/common/components/block/concept-list-block.tsx, src/common/components/matomo/index.tsx, src/common/components/matomo/matomo.test.tsx, src/pages/_app.tsx
Add Matomo integration. It is disabled in local/development by default. And in dev/test/prod servers it tries to use configs defined in environment variables.
No visual changes in this PR.
YTI-1780
=> Matomo integration

src/common/components/filter/reset-all-filters-button.test.tsx, src/common/utils/hooks/useUrlState.ts
The reset filter button was still rendered after it was clicked. It occurred when valid and draft statuses were selected but they were in a different order than in the initial state.
Fixed by sorting items so that the order doesn't matter anymore.
YTI-1804
=> Fix reset filter button status

src/common/components/filter/checkbox-filter.tsx, src/common/components/filter/filter.styles.tsx
Replace own checkbox group implementation with suomifi-ui-component's new CheckboxGroup component.
Spacings are changed by a pixel or two.
Before: 
After: 
_Note: Screenshots are taken from different environments so ignore counts._
YTI-1805
=> Use CheckboxGroup component from suomifi-ui-components

public/locales/en/admin.json, public/locales/fi/admin.json, src/common/components/info-dropdown/info-expander.tsx, src/common/components/new-concept-modal/index.tsx, src/common/components/new-concept-modal/new-concept-modal.styles.tsx, src/modules/new-concept/index.tsx, src/modules/new-concept/new-concept.styles.tsx, src/pages/terminology/[terminologyId]/new-concept.tsx, src/pages/terminology/[terminologyId]/new-concept/[conceptName].tsx
- Added modal for creating new concept
- Modal directs to new page called `new-concept` where user finishes creating the concept. Currently there is only a blank page to allow other developers to create needed components
- `new-concept` takes terms in url params (e.g. `sanastot.fi/terminology/abc-def/new-concept?fi=uusitermi&en=newterm`)
Modal button in terminology information:
Modal opened:
Current state of new-concept -page:
Title is received from values retrieved from modal
=> Yti 1814 concept base

src/common/components/matomo/index.tsx
Temporarily dump env vars to console for debugging purposes.
=> DEBUG: dump matomo env vars in console

src/common/components/info-dropdown/info-expander.tsx, src/common/components/new-concept-modal/index.tsx
In the new Concept modal, the preferred term was asked always in Finnish, Swedish, and English. Change this by using languages of the terminology.
YTI-1814
=> Use terminology's languages when creating new concept

docs/matomo.md, next.config.js, src/common/components/common-context-provider/index.tsx, src/common/components/filter/filter.styles.tsx, src/common/components/matomo/index.tsx, src/common/components/matomo/matomo.test.tsx, src/common/components/media-query/media-query-context.tsx, src/common/utils/create-getserversideprops.ts, src/layouts/error-layout.tsx, src/layouts/layout.tsx, src/pages/404.tsx, src/pages/500.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/own-information.tsx, src/pages/search.tsx, src/pages/terminology/[terminologyId].tsx, src/pages/terminology/[terminologyId]/collection/[collectionId].tsx, src/pages/terminology/[terminologyId]/concept/[conceptId].tsx, src/pages/terminology/[terminologyId]/new-concept.tsx
Environment variables can be accessed only on the server. If they are needed in the browser they must be passed via props. Made this easier by creating CommonContextProvider that is used on every page and takes all the page props. Currently, other components can access these values by simply using this context.
The first two use cases for CommonContextProvider are Matomo and guessing results of media queries in SSR. Later it would be useful with e.g. feature flags.
YTI-1800
=> Use environment variables with Matomo

Dockerfile
At this point, it will be passed there always but in the following PR, I'll include it conditionally. I excluded it from this PR as copying a file if it exists is a little tricky task in Dockerfile.
No visual changes in this PR.
=> Include coverage dir in docker image

Dockerfile, build.sh, package.json
Add SKIP_COVERAGE build argument. If it is passed (e.g. via environment variables), the coverage directory is excluded from the built image. The idea is to not bloat the production image with development-related stuff.
YTI-1890
=> Add SKIP_COVERAGE build argument

.env, src/common/components/admin-controls/admin-controls.slice.tsx, src/common/utils/create-getserversideprops.ts, src/common/utils/has-permission.tsx, src/common/utils/has-permissions.test.ts, src/store/index.tsx
`ADMIN_CONTROLS_DISABLED` can be added as an environmental variable to disable admin actions. If variable isn't defined, controls are enabled for users with admin rights.
=> hasPermission checks if admin controls are enabled

src/common/components/filter/reset-all-filters-button.test.tsx, src/common/components/search-results/search-count-tags.test.tsx, src/common/components/terminology-search/terminology-search.slice.tsx, src/common/components/vocabulary/vocabulary.slice.tsx, src/common/utils/hooks/useUrlState.test.ts, src/common/utils/hooks/useUrlState.ts, src/modules/terminology-search/index.tsx, src/modules/vocabulary/index.tsx, src/pages/terminology/[terminologyId].tsx
* Remove default selections (DRAFT, VALID) from search
* Add current language to search payload for sorting
Backend changes in [this PR](https://github.com/VRK-YTI/yti-terminology-api/pull/55)
=> YTI-1871 Status search and sorting

src/common/components/block/term-block.tsx, src/common/components/relational-information-block/render-concepts.tsx, src/common/components/search-results/search-results.tsx, src/common/components/term-modal/index.tsx, src/common/components/title/title.tsx, src/modules/concept/index.tsx
Sometimes status is incorrectly empty or missing in the backend. In these situations use "draft" as a status instead of nothing.
YTI-1924
=> Use draft as default status when rendering

src/common/components/authentication-panel/user-info.tsx, src/common/components/impersonate/use-fakeable-users.ts, src/common/components/login-modal/login-modal.tsx
Set the target to include language in login and logout api calls
- Logout and login will redirect user to frontpage with /{i18n.language} as the path.
=> Language should stay after login/logout

public/locales/en/admin.json, public/locales/fi/admin.json, public/locales/sv/admin.json, src/common/components/relational-information-block/index.tsx, src/common/components/relational-information-block/render-concepts.tsx, src/modules/edit-collection/index.tsx, src/modules/new-concept/basic-information/concept-basic-information.tsx, src/modules/new-concept/concept-terms-block/concept-terms-block.styles.tsx, src/modules/new-concept/concept-terms-block/index.tsx, src/modules/new-concept/concept-terms-block/new-term-modal.tsx, src/modules/new-concept/index.tsx, src/modules/new-concept/new-concept.styles.tsx, src/pages/terminology/[terminologyId]/collection/[collectionId]/edit.tsx
Add help text to the new term modal.
Render also the terminology's name in the relation chip if the target concept is not in the same terminology.
Turn a list of expanders into an expander group in relation modal.
Change remove term button style to match the design.
Fix some broken texts.
=> Fix a bunch of small UI issues

src/common/components/terminology-search/terminology-search.slice.tsx
Changed frontpage search not to filter by language by default. Default preferred language is still fi. 
Unless specified all terminologies will be shown unless otherwise specified by filtering.
Integration tests for checking that the search is correct should probably be done on the api side
=> YTI-1980: Frontpage default language filtering should be removed

src/modules/edit-collection/concept-picker/concept-picker.styles.tsx, src/modules/edit-collection/concept-picker/picker-modal.tsx
- Changed TextInput to SearchInput in concept search to support "Enter" key press
- Previously if user had searched for a concept and selected one of the results, the HTML tags would have been carried to selected chips. For example if user searched for "concept" and selected one, the chip would have displayed the value as `<b>concept</b>`
- Fixed bug with Chips when multiple concepts are selected. 
YTI-2008, YTI-2009, YTI-2010
=> Fixed bugs

public/locales/en/admin.json, public/locales/fi/admin.json, public/locales/sv/admin.json, src/common/components/copy-terminology-modal/copy-terminology-modal.test.tsx, src/common/components/copy-terminology-modal/copy-terminology-modal.tsx, src/common/components/copy-terminology-modal/index.tsx, src/common/components/info-dropdown/info-expander.tsx, src/common/components/vocabulary/vocabulary.slice.tsx, src/common/interfaces/vocabulary.interface.ts
Changelog:
- New button on drop-down info of terminology
- Open modal for copying terminology as a base
- New connection to backend api endpoint for copying as a base
- translations for english and finnish for all related components
- unit tests for checking if components are rendered properly
=> YTI-1995: Kopioi pohjaksi toiminto

src/modules/edit-concept/generate-concept-test-expected.tsx, src/modules/edit-concept/generate-concept.test.tsx, src/modules/edit-concept/generate-concept.tsx
- Fixed a bug with concept's uri going missing. Initial values are checked when generating object used in API and added if necessary. Also removed `code` and `uri` keys from added to object if initial values isn't provided (when creating new concept both of these key-value pairs are left out)
=> Fixed bug with concept's uri going missing

src/modules/edit-collection/index.tsx, src/modules/edit-concept/form-footer.tsx, src/modules/edit-concept/index.tsx, src/modules/edit-vocabulary/index.tsx
- Replaced router.push() to router.replace() in create and edit pages to disable them from going to browser history. This way if users want to go back in history, they don't wind up in editable pages accidentally.
=> Added replace() to sites we don't want in history

src/common/components/block/concept-list-block.tsx, src/common/components/block/property-block.tsx, src/common/components/info-dropdown/info-expander.tsx, src/common/components/property-value/get-property-value.ts, src/common/components/property-value/index.tsx, src/common/components/property-value/property-value.test.tsx, src/common/components/relational-information-block/index.tsx, src/common/components/relational-information-block/render-concepts.tsx, src/common/components/search-results/search-results.tsx, src/common/components/sidebar/sidebar-section.tsx, src/common/components/term-modal/index.tsx, src/common/components/title/title.tsx, src/modules/collection/index.tsx, src/modules/concept/administrative-details-expander.tsx, src/modules/concept/diagrams-and-sources-expander.tsx, src/modules/concept/index.tsx, src/modules/edit-collection/index.tsx, src/modules/edit-concept/index.tsx, src/modules/edit-vocabulary/generate-initial-data.ts, src/modules/edit-vocabulary/index.tsx, src/modules/own-information/index.tsx, src/modules/vocabulary/index.tsx, src/pages/terminology/[terminologyId].tsx, src/pages/terminology/[terminologyId]/collection/[collectionId].tsx, src/pages/terminology/[terminologyId]/collection/[collectionId]/edit.tsx, src/pages/terminology/[terminologyId]/concept/[conceptId].tsx
Changelog:
- Remove fallback language parameter
- Now as default fallback language will go from fi -> en -> sv
- All fallback languages were using fi anyways
- if no language was specified just return the properties without filtering
- Causes last fallback language to be first property value in list
=> Yti 2042 get property better fallback

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/relational-information-block/index.tsx, src/common/components/relational-information-block/render-chosen.tsx, src/common/components/relational-information-block/render-concepts.tsx, src/common/components/search-results/search-results.tsx
- Concepts that don't have preferred labels would have crashed the program. This error occurred in `search-results` and `relational-information`.
=> Possibly empty label doesn't cause app to crash

src/common/utils/hooks/use-confirm-before-leaving-page/use-confirm-before-leaving-page.test.tsx, src/common/utils/hooks/use-confirm-before-leaving-page/use-confirm-before-leaving-page.tsx
When confirm is correctly enabled and the user navigates to another page using next/router the confirmation is triggered. After this, the confirmation is not disabled and so it was still enabled even if the user has navigated to a page without form at all.
Fixed this by enabling disabling confirmation automatically when the page component is is unmounted.
=> Fix don't confirm before leaving page without form

src/modules/concept/index.tsx
Changelog:
- if contact for terminology is not email set mailto as yhteentoimivuus@dvv.fi
=> YTI-1953: Always have email on mailto link

next.config.js
Changelog:
- enable experimental flag for restoring scroll on 
- this flag effects navigation based only on history. 
Cons:
- Not currently covered by next js semver
- Shows the following message when running the application
```
warn  - You have enabled experimental feature (scrollRestoration) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
```
This is the commit that shows how this flag works: 
https://github.com/vercel/next.js/commit/38bd1a024cb25923d8ea15f269a7294d073684d8
Best case scenario would be to use native scrollrestoration supported by browsers using the history api. https://developer.mozilla.org/en-US/docs/Web/API/History_API
Unfortunately right now it seems that next js …
=> YTI-2047: scrollRestoration on history

src/modules/new-terminology/new-terminology-modal.tsx
Changelog:
- remove not doing anything if userposted
This change was leftover from testing and if left like this it will not allow the user press the add vocabulary button more than once meaning if the user fixes errors and presses again it does nothing
=> YTI-1894: fix unintended change

src/modules/new-terminology/missing-info-alert.tsx
Changelog:
- Status is only checked if the key is defined in the data
- Key is not defined when first creating a new terminology
- Key is defined after creating
- When modifying the key is not removed, but value can be removed
- Error is only shown when trying to remove the status
=> YTI-2063: new terminology no status error

public/locales/en/alert.json, public/locales/fi/alert.json, public/locales/sv/alert.json, src/modules/new-terminology/new-terminology-modal.tsx
Changelog:
- All alert translations have occured -> occurred
- My spellcheck is complaining about this and all dictionaries seem to agree that is it written occurred
- Show error message if newVocabulary post gives error
- 401: no authorization shows special message
- others show generic message
=> show error messages from new terminology-modal

src/common/components/copy-terminology-modal/copy-terminology-modal.tsx
Changelog:
- use the error code from prefix to check if prefix has error
- dont send api call if there is an error
- moved setAlert from own function to disable eslint alert
=> YTI-2066: copy terminlogy error apicalls

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/info-dropdown/info-expander.styles.tsx, src/common/components/info-dropdown/info-expander.test.tsx, src/common/components/info-dropdown/info-expander.tsx, src/common/components/search-results/result-card.styles.tsx, src/common/components/search-results/result-card.test.tsx, src/common/components/search-results/result-card.tsx, src/common/components/search-results/search-results.tsx
Changelog:
- result card shows either one contributor by name or amount if more than one
- info expander on terminology lists all contributors in a row
- these are not in any specific order, the array comes from the backend
- tests
=> Yti 2062 multiple contributor info

src/common/components/terminology-components/prefix.tsx, src/common/components/vocabulary/vocabulary.slice.tsx
- Switched `getIfNameSpaceInUse` to be a mutation instead of a query. Prefix is now checked correctly after user has input value for custom prefix.
=> Fixed bug with prefix checking

docs/todo.md, next-i18next.config.js, src/common/components/locale-chooser/use-locales.ts
The Swedish UI is broken because of missing translations. It will fix automatically once the texts have been translated.
Fixed this temporarily by disabling Swedish for now. Also added reverting instructions to the docs directory.
YTI-2073
=> feat: disable Swedish temporarily

src/modules/new-terminology/new-terminology-modal.tsx
- After a new terminology has been successfully created, user is redirected to the newly created terminology page instead of just closing the modal. If backend doesn't for some reason return the ID of the new terminology, just close the modal instead of redirecting to an empty page
=> User is redirected after terminology creation

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/info-dropdown/info-expander.tsx, src/modules/concept/index.tsx
- Added missing contact information to terminology expander
- Updated email title from concept ID to more descriptive one
=> Added missing contact info and changed email title

src/common/components/search-results/result-card-expander.tsx
- If deepHits-object doesn't have a uri defined, don't wrap it in a `Link`
=> Added variant if deepHit doesn't have uri defined

src/modules/new-terminology/info-file.tsx
- If user uploaded a file via file explorer and had uploaded a file that wasn't of type xlsx, a wrong error message was displayed. Now user receives a error message that explains that given file was of a wrong kind instead a general error message
=> Fixed which error message is displayed

src/common/components/title/title.tsx
Changelog:
- remove titleRef so history scrolling works on concept listing as well
=> YTI-2047: Fix history scrolling on concept listing

src/common/components/info-dropdown/info-expander.tsx, src/common/utils/has-permission.tsx, src/common/utils/has-permissions.test.ts, src/modules/collection/index.tsx, src/modules/concept/index.tsx
- Tweaked `hasPermission()` and added new unit tests
- Added terminology object as a fallback for `hasPermission` in concept page to ensure that terminology ID is passed to function
=> Yti 2108 permission bugfix

public/locales/en/alert.json, public/locales/fi/alert.json, public/locales/sv/alert.json, src/common/components/terminology-components/contact-info.tsx, src/common/components/terminology-components/information-domains-selector.tsx, src/common/components/terminology-components/language-block.tsx, src/common/components/terminology-components/language-selector.tsx, src/common/components/terminology-components/organization-selector.tsx, src/common/components/terminology-components/prefix.tsx, src/common/components/terminology-components/type-selector.tsx, src/common/utils/translation-helpers.ts, src/modules/new-terminology/info-manual.tsx, src/modules/new-terminology/new-terminology-modal.tsx, src/modules/new-terminology/status-selector.tsx
Changelog:
- Added the ability to disable all add terminology modal form fields
- Disable all add terminology modal form fields if there is an API call error
- Show errors on the bottom of the modal instead of behind the modal.
- Added translations to translation helper for HTTP codes
=> Yti 2076 error modal exitonly

public/locales/en/collection.json, public/locales/fi/collection.json, public/locales/sv/collection.json, src/common/components/terminology-components/organization-selector.tsx, src/modules/collection/index.tsx
- Changed `organization-selector` in new terminology creation modal to use `HasPermission()`
- Added missing translations
=> Changed organization selector to use HasPermission()

public/locales/en/admin.json, public/locales/en/common.json, public/locales/fi/admin.json, public/locales/fi/common.json, public/locales/sv/admin.json, public/locales/sv/common.json, src/common/components/info-dropdown/info-expander.tsx, src/common/components/new-concept-modal/index.tsx, src/modules/terminology-search/terminology-search.styles.tsx, src/modules/vocabulary/index.tsx, src/modules/vocabulary/vocabulary.styles.tsx
Changelog:
- Simplified add concept component to only have the button
- Removed translations and added new ones
- Moved button to the ResultCardWrapper instead of info-expander
- Added title next to the buttons
- Title expands by default so the buttons will be on the right side
=> YTI-2109: moved button to below expander

src/modules/edit-concept/generate-concept.tsx
Uri or code cannot be empty, because in that case termed won't generate value for them
=> YTI-2100 fix default values for code and uri

src/common/components/search-results/result-card-expander.tsx, src/common/components/search-results/search-results.tsx
It doesn't make sense to use uri.suomi.fi links in internal links. Use relative links instead, e.g. `/terminology/:terminologyId/concept/:conceptId`
=> YTI-2130 use relative links in search results

src/common/components/matomo/index.tsx, src/common/components/matomo/matomo.test.tsx
`enableJSErrorTracking` added as a new parameter for Matomo requests for logging possible errors to the service.
=> Enabled JS error tracking to matomo reports

public/locales/en/admin.json, public/locales/fi/admin.json, public/locales/sv/admin.json, src/common/components/concept-import/concept-import-modal.test.tsx, src/common/components/concept-import/concept-import-modal.tsx, src/common/components/concept-import/index.tsx, src/common/components/excel/excel.error.md, src/common/components/excel/excel.error.tsx, src/common/components/excel/excel.slice.tsx, src/common/utils/translation-helpers.ts, src/modules/new-terminology/file-upload.tsx, src/modules/new-terminology/info-file.tsx, src/modules/vocabulary/index.tsx
Changelog:
- Import concept button next to add concept button
- Opens modal where you can upload a file.
- Shows errors if there is a excel parsing error
- tests
=> YTI-2060: added concept import modal

src/common/components/modify/modify.slice.tsx, src/modules/edit-concept/generate-concept-test-expected.tsx, src/modules/edit-concept/generate-concept.test.tsx, src/modules/edit-concept/generate-concept.tsx, src/modules/edit-concept/index.tsx
Previously data sent to API looked something like this:
`data: delete: [], save: [{ ... }]`
where `delete` key would always have an empty array. Now if a term is removed from a concept it's id and other information is added to delete array as an object.
=> API call delete key is used when deleting term

src/common/components/relational-information-block/index.tsx, src/modules/edit-concept/generate-concept.tsx, src/modules/edit-concept/generate-form-data-test-variables.tsx, src/modules/edit-concept/generate-form-data.tsx, src/modules/edit-concept/index.tsx
- Closing relational data modal with 'Cancel' button no longer removes previous data
- Relating to this `generateFormData` was fixed to target correct ID's when adding data of relations from other terminologies
=> Fixed random removals & a bug with generating data

src/common/components/relational-information-block/relational-modal-content.tsx
- Previously when searching for related concepts in edit concept page that were from other terminologies, clearing search filter would immediately search for all concepts. Now when user clears the search filter the search results are cleared and a request isn't send to the back end.
=> Tweaked concept search func when fromOther

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/info-dropdown/info-expander.tsx, src/common/interfaces/vocabulary.interface.ts, src/modules/edit-vocabulary/index.tsx, src/modules/new-terminology/generate-new-terminology.tsx
- Added information about which terminology a copied terminology was copied from
=> Copied from information added

public/locales/en/admin.json, public/locales/en/alert.json, public/locales/fi/admin.json, public/locales/fi/alert.json, public/locales/sv/alert.json, src/common/components/info-dropdown/info-expander.tsx, src/common/components/removal-modal/index.tsx, src/modules/edit-concept/concept-terms-block/concept-terms-block.styles.tsx, src/modules/edit-concept/concept-terms-block/new-term-modal.tsx
- Downloading terminology as excel won't open new window to download
- Moved terms language picker upper in the form
- Fixed translations
If a recommended term has already been set with a language, user cannot choose to set the term as a recommended term
=> Added minor bug fixes

src/common/components/relational-information-block/index.tsx, src/common/components/relational-information-block/relational-modal-content.tsx, src/common/components/relational-information-block/render-chosen.tsx, src/common/components/relational-information-block/render-concepts.tsx, src/modules/edit-concept/generate-concept.tsx, src/modules/edit-concept/generate-form-data-test-variables.tsx, src/modules/edit-concept/generate-form-data.tsx
- Initial relational concepts from other terminologies are now displayed when opening modal. Previously information of these concepts was partly initialized _only_ after a call to backend was made. Now information of these concepts are built entirely from initial data received at page load.  
- Tweaked `generateConcept()` (again) to remove unnecessary terms appearing under delete key and target correct IDs. These were incorrectly tagged terms appearing in relational concepts that are from same terminology as edited concept.
=> Concept link initialization bugfix

src/pages/terminology/[terminologyId]/collection/[collectionId].tsx, src/pages/terminology/[terminologyId]/concept/[conceptId].tsx
- If a concept or collection page is loaded that doesn't have a valid ID, redirect user to /404. This has happened with some concept links where concept is from other terminology and a bug related to that. These broken ID links shouldn't appear after that PR (https://github.com/VRK-YTI/yti-terminology-ui/pull/283) has been merged but this is PR ensures that there are no breaking errors.
=> Opening falsely ID'd concept/collection bugfix

src/modules/edit-concept/concept-terms-block/concept-terms-block.styles.tsx, src/modules/edit-concept/concept-terms-block/index.tsx, src/modules/edit-concept/concept-terms-block/new-term-modal.tsx, src/modules/edit-concept/concept-terms-block/term-form.tsx
- Homographic number in other terms had a bug where users couldn't change the value or remove the homographic number tag. This was caused by an error where duplicate id's caused the update to only target the first preferred term. This was fixed by making id's truly unique.
- Fixed styling with homographic number input
=> Yti 2200 edit homograph

src/modules/edit-concept/concept-terms-block/concept-terms-block.styles.tsx, src/modules/edit-concept/concept-terms-block/new-term-modal.tsx, src/modules/edit-concept/concept-terms-block/term-form.tsx
- Term equivalency added to be visible and editable in term expander in concept edit page
=> Term equivalency visible in term edit

public/locales/en/admin.json, public/locales/fi/admin.json, public/locales/sv/admin.json, src/common/utils/translation-helpers.ts, src/modules/edit-concept/concept-terms-block/term-expander.tsx, src/modules/edit-concept/concept-terms-block/term-form.tsx, src/modules/edit-concept/validate-form.tsx
- Older terminologies might have term conjugation set to any string value. This is now taken into consideration when validating concept before payload is sent to back end. If any term has an incorrect value (e.g. not 'singular' or 'plural') set in conjugation, an error is displayed in the footer with other possible errors.
=> Incorrect term conjugations handling added

public/locales/en/admin.json, public/locales/fi/admin.json, public/locales/sv/admin.json, src/modules/edit-concept/basic-information/other-information.tsx, src/modules/edit-concept/generate-concept-test-expected.tsx, src/modules/edit-concept/generate-concept.tsx, src/modules/edit-concept/generate-form-data-test-variables.tsx, src/modules/edit-concept/generate-form-data.tsx
- Word class block in concept basic information has been removed due to it being marked as unused.
=> Removed word class option from concept information

public/locales/en/admin.json, public/locales/fi/admin.json, public/locales/sv/admin.json, src/common/utils/to-uri.test.ts, src/common/utils/to-uri.ts, src/common/utils/translation-helpers.ts, src/modules/edit-concept/basic-information/concept-diagrams-and-sources.tsx, src/modules/edit-concept/basic-information/diagrams.tsx, src/modules/edit-concept/generate-concept-test-expected.tsx, src/modules/edit-concept/generate-concept.test.tsx, src/modules/edit-concept/generate-concept.tsx, src/modules/edit-concept/index.tsx, src/modules/edit-concept/validate-form.tsx
- Simple validation added to diagram uri. `http://` or `https://` is added to diagram uri in payload if one is missing. This fixes the bug where incorrect uri would be made into nextjs internal link.
- Form validation expects the link to have at least one full stop (`.`) to accepts data as a proper link. This could be improved at some point.
- Form validation is called if user has tried to submit changes with an error/errors and makes changes after that until all errors are cleared. So now fixed errors in form data aren't visible after they have been fixed.
=> Added some validation to diagram url

src/modules/collection/index.tsx, src/modules/concept/index.tsx
YTI-2187
- Removed unnecessary permission check that caused an error to occur in concept page when accessing it through an internal link. This has been fixed in collection page as well.
=> Fixed error with moving to related concept page

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/filter/filter.styles.tsx, src/common/components/filter/reset-all-filters-button.tsx, src/common/components/footer/footer.tsx, src/common/components/navigation/desktop-navigation.tsx, src/common/components/search-results/search-count-tags.styles.tsx, src/common/components/search-results/search-count-tags.tsx, src/common/components/title/title.styles.tsx, src/common/components/title/title.tsx, src/common/utils/hooks/use-url-state/index.ts, src/common/utils/hooks/use-url-state/use-url-state.test.ts
- Suomi.fi logo in the footer resized to be smaller
- Terminology type (either terminological or other terminology) is shown in terminology title next to terminology status badge
- Filtering with language adds chosen language to badges where other active filters are
- Text added to filter badge block when there are no active filters
- Fixed font styling in a few places (filter title for example)
- Displaying collections in terminology isn't considered to be a active filter value anymore e.g. resetting filter button does not appear when collections are selected. Filtering works otherwise in the same way but changing between collections and concepts is done manually by user always.
=> Bunch of smaller changes

src/common/components/info-dropdown/info-expander.tsx
- Response type changed to array buffer in terminology download to fix bug where `.xlsx` would be corrupted
=> Axios response type added to excel download

src/common/components/title/title.tsx, src/modules/concept/index.tsx
Removed the top bar contributor from both terminology and concept page as its shown afterwards and didnt show all contributors
=> YTI-2196: remove contributor from terminology and concept

terminology-ui/src/common/components/relational-information-block/relational-modal-content.tsx
Changelog: 
- don't set selectedConcepts when doing a first search.
- selectedConcepts stay the same and the UI knows to check the checkboxes anyway
=> YTI-2210: relational concepts stay checked

terminology-ui/src/pages/api/auth/logout.ts, terminology-ui/src/store/api-base-query.ts, terminology-ui/src/tests/login.test.ts
This is to work around an issue where JSESSIONID is sometimes not enough.
=> Pass Shibboleth session cookie to API calls in SSR

terminology-ui/src/pages/api/auth/callback.ts, terminology-ui/src/pages/api/auth/fake-login.ts
- Add `host` and `x-forwarded-for` headers for shibboleth if using yti-auth-proxy
- Do not add `JSESSIONID` cookie to response when using eDuuni login
=> YTI-2178 Shibboleth fake login

terminology-ui/README.md, terminology-ui/src/modules/concept/index.tsx, terminology-ui/src/modules/edit-concept/concept-terms-block/term-expander.tsx, terminology-ui/src/modules/edit-concept/concept-terms-block/term-form.tsx, terminology-ui/src/pages/api/auth/callback.ts, terminology-ui/src/pages/api/auth/fake-login.ts, terminology-ui/src/tests/login.test.ts
- If term conjugation had been previously set to other than the current possible values (singulary/plural) the incorrect value wasn't shown in the form. Now the incorrect value is shown in the component so that users can actually change or remove the term conjugation value.
- Fixed callback unit tests that block build
=> Incorrect TermConjugation data is shown by default

datamodel-ui/src/common/utils/get-language-version.ts, datamodel-ui/src/modules/front-page/front-page-filter.tsx, datamodel-ui/src/modules/front-page/index.tsx
- `getPropertyLanguageVersion()` added to get different language versioned values from a JSON-LD type property. This fixes the bug in front page when user changed language to English and some organization didn't have a name defined in that language
=> Improved language versioned data fetching

.husky/pre-commit, common-ui/.lintstagedrc.js, common-ui/package.json, datamodel-ui/.lintstagedrc.js, datamodel-ui/package.json, package-lock.json, package.json
Changelog:
- husky install onto monorepo base
- lint-staged into all project folders (terminology-ui already added from before)
- next lint and prettier on datamodel (terminology already had)
- prettier on common-ui (next lint requires pages folder, is it possible to ignore this issue somehow?)
- added all project folders into husky pre-commit
=> YTI-2242: Enable husky and set it up for all monorepo projects

terminology-ui/public/locales/en/admin.json, terminology-ui/public/locales/fi/admin.json, terminology-ui/public/locales/sv/admin.json, terminology-ui/src/common/components/terminology-components/contact-info.tsx, terminology-ui/src/modules/new-terminology/info-manual.tsx, terminology-ui/src/modules/new-terminology/missing-info-alert.tsx
- Email validation added to new terminology creation modal
- If email isn't present the fallback value is used and email is considered valid. Otherwise the input text is checked to be a valid email
=> Email validation added

terminology-ui/src/common/components/sanitized-text-content/index.tsx
- `env=env_v2` added as suffix to links that directly target concept's URI instead of the path
=> v2 env tag added to possible direct internal links

common-ui/components/filter/status-filter-radio.tsx, common-ui/components/search-results/result-card.tsx, common-ui/components/search-results/search-count-tags.tsx, common-ui/components/search-results/search-results.tsx, terminology-ui/src/common/components/relational-information-block/search.tsx
- Enter key press call `onSearch()` even though the value is empty in relational concepts modal
- Wrapped result card description in `<SanitizedTextContent/>` to display possible links correctly
=> Tweaked SearchInput and fixed desc in ResultCard

common-ui/components/sanitized-text-content/index.tsx, terminology-ui/src/common/components/info-dropdown/info-expander.tsx, terminology-ui/src/common/components/terminology-components/contact-info.tsx, terminology-ui/src/common/utils/has-permission.tsx, terminology-ui/src/modules/new-terminology/info-manual.tsx, terminology-ui/src/modules/new-terminology/missing-info-alert.tsx
- Wrapped dispatch call inside `HasPermission()` useEffect to fix render errors
- Added env tag to sanitized text like in #324 to common-ui as well. `SanitizedTextContent` could be removed in the future
- Replaced custom regex in new terminology form email validation and added a fallback email if contact information of a terminology/concept is in incorrect form
=> Fixed render errors

common-ui/components/media-query/index.tsx, datamodel-ui/src/modules/front-page/index.tsx
- `useBreakpoints()` tweaked to fix hydration errors. Now by default server renders page for large window if mobile device isn't detected. Added `useEffect()` handles view in client if the user is accessing pages in a smaller window.
- Changed div id to be unique
=> useBreakpoints() errors fixed

terminology-ui/src/modules/concept/index.tsx
Changelog:
- Search term not shown in concepts page. 
- Still shown when editing
=> YTI-2338: Search term hidden from term listing

terminology-ui/src/modules/terminology-search/index.tsx
For swapping sanastot.beta and sanastot.suomi.fi, change link to the old version to point to beta site
=> YTI-2403 change url to beta site

terminology-ui/src/modules/edit-concept/generate-concept.tsx, terminology-ui/src/modules/edit-concept/generate-form-data-test-variables.tsx, terminology-ui/src/modules/edit-concept/generate-form-data.tsx
Use node's id instead of targetId in concept relations. Target id refers to the concept in the other terminology, whereas node's id is used when referring concept link inside the terminology. When removing concept relation, using targetId didn't remove concept link node from the database, although the reference from the concept was removed.
=> YTI-2485 fix remove related concepts

datamodel-ui/src/common/interfaces/model.interface.ts, datamodel-ui/src/common/utils/get-value.ts, datamodel-ui/src/modules/model/model-edit-view.tsx, datamodel-ui/src/modules/model/model-info-view.tsx
Changelog: 
- orgs and servicecategories gotten from datamodel instead of getting them separately and mapping the label
NOTE:
Requires: https://github.com/VRK-YTI/yti-datamodel-api/pull/101
=> YTI-2433: changed to get org and service categories (groups) from datamodel

terminology-ui/src/modules/collection/index.tsx, terminology-ui/src/modules/collection/utils.tsx, terminology-ui/src/modules/concept/index.tsx, terminology-ui/src/modules/concept/utils.tsx
- Changed to `useGetBlockData()` to `getBlockData()` and `useMemo()` solution to fix concept and collection information loading in production builds
=> Changed getBlockData functionality

terminology-ui/src/common/components/relational-information-block/render-concepts.tsx, terminology-ui/src/modules/edit-concept/generate-form-data-test-variables.tsx, terminology-ui/src/modules/edit-concept/generate-form-data.tsx, terminology-ui/src/modules/edit-concept/new-concept.types.tsx
Add an additional proeprty `targetId` to related concept. This is used in concept search modal to determine whether the concept is selected or not and avoid duplicate selections
=> YTI-2485 fix default selection in reference concepts

terminology-ui/src/modules/concept/index.tsx
Moved hooks to prevent conditional hooks. Caused problems where conditional hooks were called when clicking a related concept link
=> YTI-2502: fixed hooks when opening related concept

datamodel-ui/src/modules/as-file-modal/index.tsx, datamodel-ui/src/modules/model/model-info-view.tsx, datamodel-ui/src/pages/api/getModelAsFile.ts
Changelog:
- File name is sent through as current language label
- added file type to filename since chrome doesn't play nice with the Content-Type header
=> YTI-2531: datamodel file name and added filetype to chrome

datamodel-ui/src/common/interfaces/visualization.interface.ts, datamodel-ui/src/modules/graph/edge-corner.tsx, datamodel-ui/src/modules/graph/graph.styles.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/labeled-edge.tsx, datamodel-ui/src/modules/graph/node.tsx, datamodel-ui/src/modules/graph/splittable-edge.tsx, datamodel-ui/src/modules/graph/util.test.data.ts, datamodel-ui/src/modules/graph/utils.test.ts, datamodel-ui/src/modules/graph/utils.ts
- Support for custom edges added. Users can add corners (=invisible nodes) to an association between two class nodes to draw the edge to their liking.
- Linked attributes are shown in class nodes in graph
=> Datamodel yti 2565 resource render

datamodel-ui/src/modules/class-view/class-view.tsx
Pass attribute's model id to rendering component, because it might refer to an external data model
=> YTI-2591 use attribute's model id in fetch

datamodel-ui/public/locales/en/common.json, datamodel-ui/public/locales/fi/common.json, datamodel-ui/public/locales/sv/common.json, datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/resource-list/index.tsx, datamodel-ui/src/common/components/resource-list/resource-list.styles.tsx, datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts, datamodel-ui/src/common/interfaces/internal-class.interface.ts, datamodel-ui/src/common/interfaces/search-internal-classes.interface.ts, datamodel-ui/src/common/utils/translation-helpers.ts, datamodel-ui/src/modules/association-modal/index.tsx, datamodel-ui/src/modules/attribute-modal/index.tsx, datamodel-ui/src/modules/class-modal/index.tsx, datamodel-ui/src/modules/class-restriction-modal/index.tsx, datamodel-ui/src/modules/front-page/index.tsx, datamodel-ui/src/modules/model-form/index.tsx
- use separate endpoint when searching resources in modals (see [backend changes](https://github.com/VRK-YTI/yti-datamodel-api/pull/141/))
- display data model and concept information in search results
- remove old translations for core data model (Tietokomponenttikirjasto)
=> YTI-2578 search modal extended info

terminology-ui/src/common/utils/compare-locals.ts, terminology-ui/src/modules/concept/utils.tsx
compareLocales method returns 0 when comparing values with the same locale. This might cause that the list in not in the same order in different browsers. Added an extra step to compare functionality that the property list is mapped by language and sorting is performed based on language key.
=> YTI-2612 Fix ordering properrty lists

datamodel-ui/public/locales/en/common.json, datamodel-ui/public/locales/fi/common.json, datamodel-ui/public/locales/sv/common.json, datamodel-ui/src/modules/as-file-modal/index.tsx, datamodel-ui/src/modules/class-view/application-profile-flow.tsx, datamodel-ui/src/modules/class-view/class-view.tsx, datamodel-ui/src/modules/common-view/common-view-content.tsx, datamodel-ui/src/modules/common-view/index.tsx, datamodel-ui/src/modules/delete-modal/index.tsx, datamodel-ui/src/modules/documentation/index.tsx, datamodel-ui/src/modules/model/index.tsx, datamodel-ui/src/modules/model/model-info-view.tsx, datamodel-ui/src/modules/resource-picker-modal/index.tsx
- URI field brought back with `Copy to clipboard`-button
- Modals opened from model, class and resource actions tooltip no longer disappear suddenly
- Documentation tab supports new languages update
- Class creation in application profile no longer crashes when `isDefined` value is missing
=> Minor bugfixes

datamodel-ui/src/common/components/class/class.slice.tsx, datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/common/components/resource/resource.slice.tsx, datamodel-ui/src/modules/documentation/index.tsx, datamodel-ui/src/modules/linked-data-form/index.tsx, datamodel-ui/src/modules/model/model-edit-view.tsx
- Use different endpoints for libraries and profiles
- Rename path /ontology -> /library
See also backend changes: https://github.com/VRK-YTI/yti-datamodel-api/pull/148
=> YTI-2425 Use separate endpoint for each model type

datamodel-ui/src/common/components/resource/resource.slice.tsx, datamodel-ui/src/modules/resource/index.tsx, datamodel-ui/src/modules/resource/resource-modal/index.tsx
Changelog:
- Fix application profile creation, broken due to wrong endpoint path from frontend
- All application profile modals (attribute, association, class) now can filter with datamodel type
=> YTI-2643: Added datamodel type to resources and fix endpoint

datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/modules/model/search-view.tsx, datamodel-ui/src/modules/resource/index.tsx, datamodel-ui/src/modules/resource/resource-info/index.tsx, datamodel-ui/src/modules/resource/utils.ts, datamodel-ui/src/pages/model/[...slug].tsx
Support to view external resources 
- add model id to globalSelected object
- add curie to uri in case of external resource, e.g. `/model/profile/model_id/attribute/ext:test-attribute`
- remove setting currentResource id because the same information is available in globalSelected -object
=> YTI-2624 handle external resources in the list

datamodel-ui/src/modules/documentation/index.tsx
- Canceling documentation editing correctly resets change detection
=> Fixed buggy state in documentation page

datamodel-ui/src/common/utils/get-organizations.ts, datamodel-ui/src/modules/model-form/generate-payload.tsx, datamodel-ui/src/modules/model-form/model-form-modal.tsx
Changelog:
YTI-2648:  all names for chosen language have to be inputted
YTI-2647:  if a name has not been not been inputted show error and dont submit
YTI-2650: organization not having a translated name caused a crash on when closing the multiselect
=> Fix crash bugs and languages have to be inputted properly

datamodel-ui/src/modules/linked-model/index.tsx
Changelog:
Fix ternary operator adding http at the end of external namespaces
=> YTI-2651: Fix ternary operator adding http to external ns

datamodel-ui/src/common/components/class/class.slice.tsx, datamodel-ui/src/common/interfaces/class-form.interface.ts, datamodel-ui/src/common/interfaces/class.interface.ts, datamodel-ui/src/modules/class-form/index.tsx, datamodel-ui/src/modules/class-view/utils.ts, datamodel-ui/src/modules/common-view-content/index.tsx
- `equivalentClass` and `subResourceOf` in `Class` type changed to possibly be undefined which better reflects real life cases
- Changed an incorrect translation
=> Tweaked Class typing and replaced translation

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/common/components/namespaces/namespaces.slice.ts, datamodel-ui/src/common/utils/get-value.ts, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/common-view-content/index.tsx, datamodel-ui/src/modules/linked-model/index.tsx, datamodel-ui/src/modules/linked-model/linked-model.styles.tsx, datamodel-ui/src/modules/model-form/generate-payload.tsx, datamodel-ui/src/modules/model-form/model-form.styles.tsx, datamodel-ui/src/modules/model/generate-payload.tsx, datamodel-ui/src/modules/model/model-info-view.tsx, datamodel-ui/src/store/index.tsx
- Fetch available namespaces from backend (see [changes](https://github.com/VRK-YTI/yti-datamodel-api/pull/160)) and populate results to SingeSelect component
- Some style fixes in the namespace modal
- Add constant for admin email
=> YTI-2627 Namespace selection

datamodel-ui/src/common/components/visualization/visualization.slice.tsx, datamodel-ui/src/common/interfaces/visualization.interface.ts, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/util.test.data.ts, datamodel-ui/src/modules/graph/utils.ts
Backend changes: https://github.com/VRK-YTI/yti-datamodel-api/pull/164
- Change visualization response type 
- Change association property route (array) -> referenceTarget (string)
=> YTI2693 change visualization response type

datamodel-ui/package.json, datamodel-ui/src/common/components/model-tools/download-picture.tsx, datamodel-ui/src/common/components/model-tools/index.tsx, datamodel-ui/src/modules/model/index.tsx, package-lock.json
- Added `html-to-image` dependency for graph image export
- Graph view can be exported as a `.png`
=> .png download support added

terminology-ui/src/common/components/subscription/remove-subscription.tsx, terminology-ui/src/common/components/subscription/subscription.slice.tsx, terminology-ui/src/common/interfaces/subscription.interface.ts, terminology-ui/src/modules/own-information/index.tsx, terminology-ui/src/modules/own-information/subscription-block.tsx, terminology-ui/src/pages/own-information.tsx
- Removed unnecessary API state reset call after an email subscription/subscriptions has been unsubscribed from. The API is called already in a parent component after the unsubscribe call is successful
- Added minor refactoring and improved typing
=> Fixed glitchy email unsubscription functionality

datamodel-ui/src/common/utils/get-api-errors.ts, datamodel-ui/src/modules/resource/index.tsx, datamodel-ui/src/modules/resource/resource-info/index.tsx
Changelog:
- Due to inUse being undefined when first rendering it sets externalActive to undefined
- This has been changed to now update externalActive when inUse updates, meaning when the result from the api call comes
- This does not change functionality otherwise
- Better api errors, there might be cases where details is string instead of object, so in those cases we just return details as string
=> YTI-2692: Fix inuse

datamodel-ui/public/locales/en/common.json, datamodel-ui/public/locales/fi/common.json, datamodel-ui/public/locales/sv/common.json, datamodel-ui/src/common/components/model-tools/index.tsx, datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/modules/common-view-content/index.tsx, datamodel-ui/src/modules/graph/edges/edge.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx, datamodel-ui/src/modules/graph/utils/convert-to-edges/convert-to-edges.test.data.ts, datamodel-ui/src/modules/graph/utils/convert-to-edges/convert-to-edges.test.ts, datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts, datamodel-ui/src/modules/graph/utils/get-connected-elements/index.ts
- Selected associations stay highlighted
- Toggle to highlight class node inbound and outbound edges
- Fixed small bug where domain and range were in incorrect order
=> Yti 2749 edge highlight improvements

common-ui/components/drawer/drawer.styles.tsx, datamodel-ui/src/modules/class-form/index.tsx, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/class-view/resource-info.tsx, datamodel-ui/src/modules/linked-data-view/index.tsx, datamodel-ui/src/modules/model/model-info-view.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx, datamodel-ui/src/modules/resource/resource-info/index.tsx
- Tooltip icon changed to correct one
- Drawer tab titles stay in same position
- Moved Save and Cancel buttons in class and resource forms to be in the top of drawer like in other tabs
- Added y-scroll support to drawer tab buttons for smaller screen users
=> Yti 2754 drawer title improvements

datamodel-ui/src/modules/code-list-modal/index.tsx, datamodel-ui/src/modules/code-list-modal/results-and-info-block.tsx, datamodel-ui/src/modules/linked-data-form/index.tsx, datamodel-ui/src/modules/linked-model/index.tsx, datamodel-ui/src/modules/resource/resource-form/components/attribute-restrictions.tsx
- Fixed submit button disabled state detection in linked code lists and data models modal. Now if changes are detected, the user can submit these correctly
- Code list modal selection changed to use json internally instead of string. Tracking just the uri of the selected code list(s) caused a bug where the code list information couldn't be fetched properly when changing search results page
- Removed few unused `console.log()`
=> Fixed button disabled state and code list changes

datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/modules/class-form/index.tsx, datamodel-ui/src/modules/class-form/utils.ts, datamodel-ui/src/modules/class-modal/index.tsx, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/documentation/index.tsx, datamodel-ui/src/modules/model-form/index.tsx, datamodel-ui/src/modules/model/model-edit-view.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx, datamodel-ui/src/modules/resource/resource-form/validate-form.ts
- Displayed error messages tweaked to be a shorter list
- Bug in `ClassModal` filter when submitting and opening the modal again and the filter values would be incorrect fixed
- Multiple groups can be added to filter instead of just one
- Spinner set to track `isLoading` instead of `userPosted`. If an error occurred in form the spinner would spin forever
=> Yti 2654 multiple error msg fix

datamodel-ui/src/common/interfaces/counts.interface.ts, datamodel-ui/src/modules/front-page/index.tsx
Changelog:
- Change counts to work with all languages
- Sort language filter by promoted then alphabetical
- Remove useless replace `uuid:` as data from backend comes without this already
=> YTI-2585: Fix language filter not showing languages

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/multi-column-search/multi-column-search.styles.tsx
- Selected groups user adds to `<MultiSelect />` in modal filter are displayed as follow:
- Nothing selected = All groups
- One selected = Selected groups name
- More than one selected = N amount selected
=> Selected groups in MultiSelect are displayed in field correctly

common-ui/components/search-results/result-card.styles.tsx, common-ui/components/search-results/result-card.tsx, common-ui/components/search-results/search-count-tags.props.ts, common-ui/components/search-results/search-count-tags.tsx, common-ui/components/title/title.styles.tsx, datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts, datamodel-ui/src/common/components/search-models/search-models.slice.tsx, datamodel-ui/src/common/interfaces/code.ts, datamodel-ui/src/common/interfaces/status.interface.ts, datamodel-ui/src/modules/front-page/front-page-filter.tsx, datamodel-ui/src/modules/front-page/index.tsx, datamodel-ui/src/modules/model-form/index.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx
Changelog:
- DRAFT and SUGGESTED use warningBase color
- VALID uses successBase color instead of manually defined
- Change status interface import on some files to match same ones in datamodel
- Default search is now VALID, SUGGESTED
- DRAFT shows only for authorized users and is hidden by default
=> YTI-3196: Change how status works

datamodel-ui/package.json, datamodel-ui/src/common/components/model-tools/model-tools.styles.ts, datamodel-ui/src/common/interfaces/graph.interface.ts, datamodel-ui/src/common/interfaces/visualization.interface.ts, datamodel-ui/src/modules/graph/edges/edge.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx, datamodel-ui/src/modules/graph/nodes/corner-node.tsx, datamodel-ui/src/modules/graph/nodes/node.styles.tsx, datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts, datamodel-ui/src/modules/graph/utils/convert-to-nodes/convert-to-nodes.test.data.ts, datamodel-ui/src/modules/graph/utils/convert-to-nodes/convert-to-nodes.test.ts, datamodel-ui/src/modules/graph/utils/convert-to-nodes/index.ts, datamodel-ui/src/modules/graph/utils/create-class-node/create-class-node.test.ts, datamodel-ui/src/modules/graph/utils/create-class-node/index.ts, datamodel-ui/src/modules/graph/utils/create-corner-node/create-corner-node.test.ts, datamodel-ui/src/modules/graph/utils/create-corner-node/index.ts, datamodel-ui/src/modules/graph/utils/create-edge/index.tsx, datamodel-ui/src/modules/graph/utils/generate-positions-payload/generate-positions-payload.test.ts, datamodel-ui/src/modules/graph/utils/generate-positions-payload/index.ts, datamodel-ui/src/modules/graph/utils/get-connected-elements/index.ts, datamodel-ui/src/modules/graph/utils/handle-corner-node-delete/index.ts, package-lock.json
- Updated React Flow to version `11.8.3` from `11.4.2`
- Improved `Node` and `Edge` typing and removed all `any` types related to graph
- Partial support for generating edges from `parentClasses`. Todo comment in code explains more in detail
- `getConnected()` improved to stop parsing edges when first class node occurs
- Fixed `UpperClass` arrow direction in edge
- Removed `createNewCornerNode()` as unused
=> Graph generation bugfixes

datamodel-ui/src/common/components/inline-list/index.tsx, datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx
This selection can't be removed, only changed to another one.
To achieve this, the InlineList now accepts deleteDisabled=true as an argument to completely disable deletion.  Previously it only allowed "false" or an array of strings.
=> prevent deleting owl:DatatypeProperty in UI

datamodel-ui/src/modules/class-form/utils.ts, datamodel-ui/src/modules/model-form/validate-form.tsx, datamodel-ui/src/modules/model/validate-form-update.tsx, datamodel-ui/src/modules/resource/resource-form/validate-form.ts
Previously validations would pass strings with only whitespaces (e.g. " "), and the validation would then fail from the backend.
To make error cases consistent, validations for empty strings are now done with an additional .trim() call.
=> check for all-whitespace in string validation

datamodel-ui/src/modules/class-form/index.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx
Some identifier validation errors were shown as "unexpected-error-title".
This change adds more errors as known errors, so they will be translated with "missing-information-title".
=> don't show some identifier validation errors as unexpected

datamodel-ui/src/common/components/model-tools/index.tsx, datamodel-ui/src/common/components/model-tools/model-tools.styles.ts, datamodel-ui/src/modules/graph/nodes/class-node.tsx
* disable unused showDomainRange for now
* remove pointer-events css since it was causing mouse clicks to go through the panel
* show class & resource ids if showById is set
=> graph tools panel tweaks

datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts, datamodel-ui/src/common/interfaces/status.interface.ts, datamodel-ui/src/common/utils/status-list.ts, datamodel-ui/src/common/utils/translation-helpers.ts, datamodel-ui/src/modules/class-form/index.tsx, datamodel-ui/src/modules/code-list-modal/filter-block.tsx, datamodel-ui/src/modules/front-page/front-page-filter.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx
- remove old statuses (INCOMPLETE, INVALID) from the list
- fix grouping statuses to 'in use' and 'not in use'
- move status-list to datamodel-ui folder, since it's datamodel specific after adding SUGGESTED
=> YTI-3388 Fix search by status

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/modules/concept-block/index.tsx
Previously this would cause all concepts from all terminologies listed, since an API call was made with an empty list of terminologies.
=> don't attempt to list concepts if model has no linked terminologies

datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/common/components/resource/resource.slice.tsx, datamodel-ui/src/common/interfaces/model-form.interface.tsx, datamodel-ui/src/common/interfaces/model.interface.ts, datamodel-ui/src/common/utils/hooks/use-initial-model-form.tsx, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/class-view/resource-info.tsx, datamodel-ui/src/modules/documentation/index.tsx, datamodel-ui/src/modules/linked-data-form/index.tsx, datamodel-ui/src/modules/linked-data-view/index.tsx, datamodel-ui/src/modules/model-form/index.tsx, datamodel-ui/src/modules/model/generate-payload.tsx, datamodel-ui/src/modules/model/index.tsx, datamodel-ui/src/modules/model/model-edit-view.tsx, datamodel-ui/src/modules/model/model-info-view.tsx, datamodel-ui/src/modules/model/prior-versions.tsx, datamodel-ui/src/modules/resource/index.tsx, datamodel-ui/src/modules/resource/resource-info/index.tsx
Changelog:
- new endpoint for editing versioned models
- get resource active now takes version parameter
- restrict editing of resources and links of versioned  datamodel.
- editing of versioned model metadata is allowed
=> YTI-3204: add edit restrictions to datamodels

common-ui/components/login-modal/index.tsx, common-ui/utils/generate-impersonate.ts
Changelog:
Encode `target` param, if not encoded the params do not work as & is seen as a separate param from `target`
`target=/fi/?status=VALID&STATUS=DRAFT`
is seen as 
target: `/fi/?status=VALID` 
status: `STATUS`
=> YTI-3231: encode uri component for passing values

datamodel-ui/src/common/components/multi-column-search/index.tsx
Changelog: 
- Service categoeries will always have "All categories" option even if the service category query fails
- This fixes null error since the dropdown menu will not be empty now'
- Minor fixes
- Remove some unnecessary useState calls and just save to constant.
- Rename variable in mapping loop for clarity
- Remove unnecessary casting to string
=> YTI-3398: fix null error on modals

common-ui/components/filter/status-filter-radio.tsx, common-ui/components/search-results/search-count-tags.tsx, common-ui/components/search-results/search-results.tsx, datamodel-ui/src/common/components/counts/counts.slice.tsx, datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts, datamodel-ui/src/common/components/search-models/search-models.slice.tsx, datamodel-ui/src/common/utils/status-list.ts, datamodel-ui/src/modules/front-page/front-page-filter.tsx, datamodel-ui/src/modules/front-page/index.tsx
Changelog:
- custom default value for front page filter with valid and draft as fallback
- if search results has default status filters, show them when no status filters set
- use global variable for status lists instead of manually defining in multiple places
=> YTI-3407: choose default status filter for datamodels

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/modules/concept-block/index.tsx
Added a button to model editing form to allow unselecting the concept.
This has some manual adjustments of button positions with `marginLeft` to get them to line up nicely.
=> allow removing concept from model

datamodel-ui/src/common/utils/get-api-errors.test.ts, datamodel-ui/src/common/utils/get-api-errors.ts, datamodel-ui/src/modules/class-form/index.tsx
In some cases, the error message in UI would only display " : ".
These changes should make sure there's always at least some error message, even though the error handling itself is not yet very expressive.
Additionally some unit tests have been added for getApiError, but it's still probably missing some error cases.
=> fix errors sometimes showing up empty

datamodel-ui/src/modules/class-form/index.tsx
This wasn't caught by CI builds for some time
* changed `AxiosQueryError` -> `AxiosBaseQueryError`
* casted `AxiosQueryErrorFields`
=> fix build error due to incorrect axios types

datamodel-ui/src/modules/class-restriction-modal/index.tsx, datamodel-ui/src/modules/class-view/application-profile-flow.tsx, datamodel-ui/src/modules/class-view/index.tsx
- Use more desrcriptive names 
- Rename nodeShape -> targetClass, because default selection is used as sh:targetClass value
=> YTI-3484 fix default sh:node selection

datamodel-ui/src/common/components/datatypes/datatypes.slice.ts, datamodel-ui/src/common/components/resource/resource-utils-data.ts, datamodel-ui/src/common/components/resource/utils.ts, datamodel-ui/src/common/interfaces/resource-form.interface.ts, datamodel-ui/src/common/interfaces/resource.interface.ts, datamodel-ui/src/modules/common-view-content/index.tsx, datamodel-ui/src/modules/resource/resource-form/components/range-and-domain.tsx, datamodel-ui/src/modules/resource/utils.ts
Store full URI for attribute's data type (e.g. http://www.w3.org/2001/XMLSchema#integer instead of xsd:integer)
=> YTI-3574 use UriData to handle attribute's data type

datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx
Changelog:
- Change class restriction nodes actions button to now do the same as in the class info buttons
=> YTI-3593: fix resource modals on application profile graph

datamodel-ui/src/modules/class-view/class-info.tsx
Added a simple `InlineAlert` if the result of the action resulted in an error.
=> show error message if adding attribute/association to a class fails

datamodel-ui/src/common/components/resource/resource.slice.tsx, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/class-view/utils.ts, datamodel-ui/src/modules/graph/nodes/class-node.tsx, datamodel-ui/src/modules/resource/index.tsx
Changelog:
- Remove automatically setting label from parent resources
- We can also remove setting empty language data for labels as its not needed for payload
- refactored resourceInitialData to return value instead of assigning a value and returning it
=> YTI-3624: remove automatic label inheritance

datamodel-ui/public/locales/en/common.json, datamodel-ui/public/locales/fi/common.json, datamodel-ui/public/locales/sv/common.json, datamodel-ui/src/common/components/model-drawer/index.tsx, datamodel-ui/src/common/components/resource-error/index.tsx, datamodel-ui/src/common/components/uri-info/index.tsx, datamodel-ui/src/common/utils/create-getserversideprops.ts, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/class-view/resource-info.tsx, datamodel-ui/src/modules/model-form/link-block.tsx, datamodel-ui/src/modules/resource/index.tsx, datamodel-ui/src/pages/404.tsx, datamodel-ui/src/pages/500.tsx, datamodel-ui/src/pages/model/[...slug].tsx
- Added `/404` and `/500` pages
- New component added for resources that can't be downloaded
- Fixed SSR - now supports version info and initial view is retrieved from Redux
- Fixed minor bug with `getEnvParam()` when `window` isn't defined
=> Yti 3602 404 page

datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/search-internal-resources/search-internal-resources.slice.ts
Changelog:
- Add current model as includeDraftFrom when having the All datamodels filter
=> YTI-3610: current model as draft in all datamodels filter

datamodel-ui/next.config.js, datamodel-ui/src/common/components/layout/index.tsx, datamodel-ui/src/common/utils/create-getserversideprops.ts, datamodel-ui/src/pages/404.tsx, datamodel-ui/src/pages/500.tsx, datamodel-ui/src/pages/model/[...slug].tsx
- Necessary Matomo configurations added
- `<Matomo />` components added and/or enabled
- `<Head />` parameters added
- Data model/[...slug] page changed to use internal `<Layout />` component instead of from `common-ui`
=> Matomo functionalities added

datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/utils/get-value.ts, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/nodes/attribute-node.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx
- Added `modelId` to all `setSelected()`. Edit views of resources selected were in an incorrect state if `modelId` wasn't found
=> Fixed a bug with resource edit view shown as blank

datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/model/model-info-view.tsx
- Removed `Update status` and `Create copy` buttons
- `Create release` functionality made available only to non-versioned data models
- `Order list` button hidden from application profiles
=> Removed unused buttons and added render conditions

datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/common/interfaces/graph.interface.ts, datamodel-ui/src/common/interfaces/visualization.interface.ts, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx, datamodel-ui/src/modules/graph/nodes/node.styles.tsx, datamodel-ui/src/modules/graph/utils/create-attribute-node/index.ts, datamodel-ui/src/modules/graph/utils/create-class-node/create-class-node.test.ts, datamodel-ui/src/modules/graph/utils/create-class-node/index.ts, datamodel-ui/src/modules/graph/utils/generate-positions-payload/generate-positions-payload.test.ts, datamodel-ui/src/modules/graph/utils/visualization-test-data/index.ts
Changelog: 
- added typing to some slice selectors (should all of them be typed
- this seemed to help  with typing when using the selector
- Added actions buttons to library graph nodes
- Simplified the button generation on code side
- Added uris to visualization for added filtering support.
=> YTI-3647: add actions to library nodes in graph

common-ui/components/search-results/result-card.tsx, common-ui/components/search-results/search-results.tsx, terminology-ui/src/modules/edit-vocabulary/generate-initial-data.test.ts, terminology-ui/src/modules/edit-vocabulary/generate-initial-data.ts, terminology-ui/src/modules/edit-vocabulary/index.tsx, terminology-ui/src/modules/terminology-search/index.tsx, terminology-ui/src/modules/vocabulary/index.tsx
- Translated languages replaced with language codes gotten from backend
- Fixed small visual bug with search result cards where too many middots were visible
=> Incorrect language labels replaced with language codes

datamodel-ui/public/locales/en/common.json, datamodel-ui/public/locales/fi/common.json, datamodel-ui/public/locales/sv/common.json, datamodel-ui/src/common/components/model-tools/download-picture.tsx, datamodel-ui/src/common/components/model-tools/index.tsx, datamodel-ui/src/common/components/model-tools/model-tools.styles.ts, datamodel-ui/src/common/utils/translation-helpers.ts
- Added tooltip to graph tools buttons with small description texts on what each button does
- Tooltip is displayed when user hovers over the button for a second
=> Added tooltips to model tools buttons

datamodel-ui/src/common/components/multi-column-search/index.tsx, datamodel-ui/src/common/components/resource-list/index.tsx, datamodel-ui/src/common/components/resource-list/resource-list.styles.tsx, datamodel-ui/src/common/utils/status-list.ts, datamodel-ui/src/modules/linked-data-form/index.tsx, datamodel-ui/src/modules/linked-model/index.tsx, datamodel-ui/src/modules/linked-model/list-form.tsx
Changes in this PR: 
- Fixed found bugs in linked data models modal
- Core models can only link to other core models. Application profiles to core models and other application profiles
- Filter for picking model type added to application profile
- Fixed table styling with larger texts
- Acceptable/valid statuses set to include only `Valid` and `Suggestion`
- Chosen chips include only newly picked and chosen values aren't dropped after updating filter
=> Fixed found bugs

datamodel-ui/src/modules/linked-model/list-form.tsx
Changelog:
- Use id instead of uri in case model is versioned.
- don't add previously selected to new selected ids since they are already in the ids list
=> YTI-3691: fix selecting versioned model

datamodel-ui/src/modules/class-form/index.tsx, datamodel-ui/src/modules/class-view/resource-info.tsx, datamodel-ui/src/modules/common-view-content/index.tsx
- Association target selection disabled in class edit view. This feature is still available in class information view
=> Disabled association target selection in class edit view

common-ui/components/drawer/drawer-content-wrapper.tsx, datamodel-ui/next.config.js, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/resource/resource-info/index.tsx
Changelog:
- Use ref callback instead of ref, this makes ref update properly.
- use margin-top instead of padding-top so that the scrollbar is not unnecessarily hidden
- remove unneeded translate3d css rule
- make class info view also have a the title as a static header
=> Datamodel yti 3704 hidden elements info

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/modules/model/model-info-view.tsx
Changelog: 
- To draft button
- The conditional rendering was done like this with separate checks for each component because the ActionMenu component requires ActionMenuItem to be a direct child for the highlighting to work.  Conditional rendering introduces the react fragment which makes it so that if multiple items are rendered under the same condition then they will not be direct children anymore
=> YTI-3664: add to draft button

common-ui/modules/own-information/index.tsx, datamodel-ui/src/common/components/organizations/organizations.slice.tsx, datamodel-ui/src/modules/front-page/index.tsx, datamodel-ui/src/modules/model-form/index.tsx, datamodel-ui/src/modules/own-information/index.tsx, datamodel-ui/src/pages/index.tsx, datamodel-ui/src/pages/model/[...slug].tsx, datamodel-ui/src/pages/own-information.tsx
changelog:
- Get child organisations when getting organisations from backend
- Hide all organisations that do not have a label. All organisations have a label when getting them so this basically filters out only deleted organisations
=> YTI-3703: show child orgs and hide deleted orgs

common-ui/components/authentication-panel/user-info.tsx
- Fixed uri changing when logging out
- This fixes the bug in both Terminologies and Data models 
- If `asPath` is passed as is the object type changes so that it passes parameters to own values under new keys. Passing it through `encodeURIComponent` keeps the value as we want
=> Fixed incorrect format of asPath

datamodel-ui/src/modules/documentation/index.tsx
In the old data there are some very long documentations. Increase max character count to 50000. Backend changes in this PR https://github.com/VRK-YTI/yti-datamodel-api/pull/261
=> YTI-3688 increase documentation max character count

common-ui/components/search-results/result-card-typed-expander.tsx, common-ui/components/search-results/search-results.tsx, datamodel-ui/public/locales/en/common.json, datamodel-ui/public/locales/fi/common.json, datamodel-ui/public/locales/sv/common.json, datamodel-ui/src/common/interfaces/datamodel.interface.ts, datamodel-ui/src/common/utils/translation-helpers.ts, datamodel-ui/src/modules/front-page/index.tsx
Changelod: 
- Add a new type of `extra` resultcard.
```ts
interface TypedExander {
deepHits: {
[key: string]: {
type: string;
label: string;
id: string;
uri: string;
}[];
};
translateResultType: (type: string, t: TFunction) => string;
translateGroupType: (type: string, t: TFunction) => string;  
}
```
- Deep hits are a map of objects where key is the `versionIri` of a modle and the list of objects are resources that made deep hits
- TranslateResultType is a translate helper function that translates a result type ('class' --> 'Luokka')
- TranslateGroupType is a translate helper function that translates a groiup type ('class' --> 'Luokat')
Results will need to be mapped to this type.so that they can be used.
There is an example in `datamodel-ui/src/modules/front-page/index.tsx` on line 246
=> YTI-3678: resource search frontpage

datamodel-ui/src/common/interfaces/datamodel.interface.ts, datamodel-ui/src/modules/front-page/index.tsx
Changed how the links are generated for resource matches in the search results.
Instead of: `https://iri.suomi.fi/model/foo/bar`
generate an internal url like: `/model/foo/attribute/bar?ver=1.2.3`
=> use versioned internal urls for resource matches in search

datamodel-ui/src/common/utils/get-language-version.ts, datamodel-ui/src/modules/class-view/resource-info.tsx, datamodel-ui/src/modules/common-view-content/index.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx
- fix duplicate ids when listing resources in class node
- use model id from router, because actions with external references refers to the wrong model id
- prefer english language when display localized content
=> YTI-3812 UI fixes found in migration

terminology-ui/src/modules/edit-concept/concept-terms-block/term-expander.tsx
Term status was always showing up as Draft in the term dropdown header.
=> Fix showing term status when editing concept

terminology-ui/src/common/components/block/multilingual-block.tsx
If the data provided to `MultilingualBlock` is empty, don't render anything.
This check was already there, but didn't take into account that the data might be an array.
Example in the concept page:
Before:
After:
=> YTI-3694 don't show empty multilingual blocks

.github/CODEOWNERS
Added `CODEOWNERS` with default reviewers.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> add CODEOWNERS with default reviewers

terminology-ui/src/common/components/info-dropdown/info-expander.test.tsx, terminology-ui/src/common/components/info-dropdown/info-expander.tsx, terminology-ui/src/common/components/terminology-components/organization-selector.tsx, terminology-ui/src/common/components/terminology-search/terminology-search.slice.tsx, terminology-ui/src/common/interfaces/terminology.interface.ts, terminology-ui/src/modules/collection/index.tsx, terminology-ui/src/modules/concept/index.tsx, terminology-ui/src/modules/own-information/index.tsx, terminology-ui/src/modules/terminology-search/index.tsx, terminology-ui/src/modules/vocabulary/index.tsx, terminology-ui/src/pages/index.tsx, terminology-ui/src/pages/own-information.tsx, terminology-ui/src/pages/terminology/[terminologyId]/edit.tsx
- Show only parent organizations in terminology, concept and collection pages
- Modify getOrganizations query by adding `showChildOrganizations` parameter
Backend changes: https://github.com/VRK-YTI/yti-terminology-api/pull/129
=> YTI-2718 filter child organizations from the public view

datamodel-ui/src/common/components/model-tools/index.tsx, datamodel-ui/src/common/components/model-tools/model-tools.styles.ts
The settings modal was previously anchored to the button that opens it, positioning it so that it sometimes goes off-screen on smaller displays.
The modal is now changed to have absolute positioning relative to the toolbar, effectively anchoring it at top right of the screen.
**Before:**
**After:**
=> change graph settings modal position

terminology-ui/src/modules/concept/utils.test.tsx, terminology-ui/src/modules/concept/utils.tsx
Sort terms only based on their language (fi, sv, others languages) and type (recommended, synonym, not recommended), not alphabetically within particular term type.
=> YTI-3693 Change terms' sorting

terminology-ui/src/common/components/info-dropdown/info-expander.tsx, terminology-ui/src/common/components/new-concept-modal/index.tsx, terminology-ui/src/common/utils/compare-locals.ts, terminology-ui/src/modules/concept/utils.tsx, terminology-ui/src/modules/edit-collection/concept-picker/expander-concept-content.tsx, terminology-ui/src/modules/edit-collection/index.tsx, terminology-ui/src/modules/edit-concept/index.tsx, terminology-ui/src/modules/vocabulary/terminology-list-filter.tsx
- Add english to language comparison
- Fix localized data and language list order: fi, sv, en, other languages in alphabetical order
- Fix also terms' order (actually related to YTI-3936) by adding index to the compare key (modules/concept/utils.tsx)
=> YTI-3824 fix localized data order

datamodel-ui/src/common/components/counts/counts.slice.tsx
Currently the front page filters are a bit confusing, when selecting groups will affect the counts of other groups.
As an attempt to make the filtering less confusing, groups are no longer taken into account when requesting counts from the backend.
=> don't pass groups to the counts endpoint

datamodel-ui/src/modules/class-view/external-resource-info.tsx, datamodel-ui/src/modules/class-view/resource-info.tsx
Skip loading if external resource. Instead, view resource's name, description and URI which are already available in the data
=> YTI-3808 show external resource info in expander

datamodel-ui/src/modules/graph/utils/visualization-test-data/index.ts, datamodel-ui/src/pages/api/auth/callback.ts, datamodel-ui/src/pages/api/getModelAsFile.ts
Fix setting request cookies when exporting datamodel as a file. 
- Set shibboleth cookie to session after login
- Use auth proxy url instead of datamodel-api url in the request (in aws env)
Fixed test data for visualization (related to https://github.com/VRK-YTI/yti-ui/pull/685)
=> YTI-3862 Fix exporting draft version

datamodel-ui/src/common/components/model-tools/index.tsx, datamodel-ui/src/modules/graph/index.tsx
The zoom buttons in the graph toolbar would zoom out to a negative value, flipping the graph.
Zoom levels are now fixed values, ranging from 0.25 to 5.
Zooming with mouse wheel is not limited to these values, but are also capped at 0.25 and 5.
[Screencast from 2024-02-22 10-58-09.webm](https://github.com/VRK-YTI/yti-ui/assets/25614946/7c59f699-a6da-4094-8ac6-eff60ba0061c)
=> fix graph zooming using toolbar

common-ui/components/pagination/index.tsx, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/model/search-view.tsx, datamodel-ui/src/modules/resource/index.tsx
"pageFrom" was still being set wrong, causing incorrectly paged API searches.
Every instance of `DetachedPagination` should now work properly:
* Switching pages works
* Last page is calculated correctly
* API calls don't have incorrectly multiplied `pageFrom` values
=> fixes to paging with DetachedPagination

datamodel-ui/src/modules/linked-model/list-form.tsx
Show search results in datamodel linking modal with empty search keyword. This way the user doesn't have to go through extra steps to get some datamodels listed.
=> show search results with no search parameter

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/common/interfaces/resource-reference.interface.ts, datamodel-ui/src/common/utils/translation-helpers.ts, datamodel-ui/src/modules/create-release-modal/index.tsx, datamodel-ui/src/modules/create-release-modal/release-model-styles.tsx
- Before release, check that all references to current and external (other models in Interoperability platform) namespaces exists ([backend changes](https://github.com/VRK-YTI/yti-datamodel-api/pull/292)). 
- Change representation of invalid resources by using ResourceReference interface
=> YTI-3939 Checking that all references exist before releasing data model

datamodel-ui/src/modules/as-file-modal/index.tsx, datamodel-ui/src/pages/api/getModelAsFile.ts
Add JSON Schema as an option for export
=> add support for JSON Schema export

datamodel-ui/src/pages/api/getModelAsFile.ts
The discrepancy with the parameter name for getModelAsFile caused JSON Schema export to do a JSON-LD export instead.
The parameter name should be the same as it is in the selection modal.
=> fix JSON Schema export not using the correct parameter

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/common/utils/translation-helpers.ts, datamodel-ui/src/modules/delete-modal/index.tsx, datamodel-ui/src/modules/model/model-info-view.tsx, datamodel-ui/src/modules/resource/resource-form/components/association-restrictions.tsx
Enable removing data models from the UI. In draft models remove button is always visible if user has permissions. In versioned data models the button is visible only for superusers. 
Backend changes: https://github.com/VRK-YTI/yti-datamodel-api/pull/298
Other bug fix: Fix selecting association's target class (sh:class). Only library class is allowed to select.
=> YTI-4042 Remove datamodels

datamodel-ui/src/common/interfaces/resource-reference.interface.ts, datamodel-ui/src/common/interfaces/visualization.interface.ts, datamodel-ui/src/modules/class-view/class-info.tsx, datamodel-ui/src/modules/class-view/index.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts, datamodel-ui/src/modules/graph/utils/generate-positions-payload/generate-positions-payload.test.ts, datamodel-ui/src/modules/graph/utils/generate-positions-payload/index.ts, datamodel-ui/src/modules/graph/utils/graph-utils/index.tsx, datamodel-ui/src/modules/graph/utils/visualization-test-data/index.ts, datamodel-ui/src/modules/resource/utils.ts
- Send corner node origin to backend. 
- Enable snapToGrid feature
Other fixes:
- Remove unused imports 
- Class add association modal: Allow select association which already added to the class if there is also range added
=> YTI-4025 Visualization fixes

datamodel-ui/next.config.js, datamodel-ui/src/pages/api/v1-redirect.ts
Create a new rewrite config for v1 URLs (ending with slash)
- /model/model-id/ -> /api/v1-redirect?modelId=model-id
- /model/model-id/resource-id/ -> /api/v1-redirect?modelId=model-id&resourceId=resourceId
In `v1-redirect` route add headers needed and call endpoint for getting redirect address (see [backend implementation](https://github.com/VRK-YTI/yti-datamodel-api/pull/306))
=> YTI-4074 redirect v1 application URLs

datamodel-ui/src/common/components/resource/resource.slice.tsx, datamodel-ui/src/common/interfaces/graph.interface.ts, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/utils/convert-to-nodes/index.ts, datamodel-ui/src/modules/graph/utils/create-attribute-node/index.ts, datamodel-ui/src/modules/graph/utils/create-class-node/index.ts, datamodel-ui/src/modules/resource/index.tsx, datamodel-ui/src/modules/resource/resource-form/index.tsx, datamodel-ui/src/modules/resource/resource-info/index.tsx
Cache tags should already exists for all API operations, which should let RTK handle re-fetching automatically.
This hopefully fixes some errors caused by manual refetching, _"Error: Cannot refetch a query that has not been started yet."._
https://redux-toolkit.js.org/rtk-query/usage/automated-refetching
Needs to be tested more before turning this Draft into PR.
=> remove manual refetching in favor of cache invalidation

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/src/common/components/class/class.slice.tsx, datamodel-ui/src/common/interfaces/notifications.interface.ts, datamodel-ui/src/common/interfaces/simple-resource.interface.ts, datamodel-ui/src/common/utils/translation-helpers.ts, datamodel-ui/src/modules/class-view/remove-code-list-modal.tsx, datamodel-ui/src/modules/class-view/resource-info.tsx, datamodel-ui/src/modules/code-list-modal/index.tsx, datamodel-ui/src/modules/common-view-content/index.tsx
- 'Add code list' option added to the action menu of library class' attributes
- Code lists are selected from the modal (same implementation for adding code list for property shape)
- Added code lists are listed with remove button in attribute's information
Backend: https://github.com/VRK-YTI/yti-datamodel-api/pull/310
Other changes:
- Add check if editing is disabled (=viewing published version) for selecting association's target 
- Show "Not defined" text if no association target has been defined for library class' association
=> YTI-4137 add code lists for library class' attributes

datamodel-ui/src/modules/model/index.tsx
Handle model as draft if new-parameter (added after creating model) is present.
=> YTI-4151 Fix redirection after creating data model

datamodel-ui/src/modules/common-view-content/index.tsx, datamodel-ui/src/modules/graph/index.tsx, datamodel-ui/src/modules/graph/nodes/class-node.tsx, datamodel-ui/src/modules/graph/nodes/node.styles.tsx, datamodel-ui/src/modules/graph/utils/convert-to-edges/index.ts, datamodel-ui/src/modules/graph/utils/get-edge-params/index.ts, datamodel-ui/src/modules/graph/utils/visualization-test-data/index.ts, datamodel-ui/src/modules/model/index.tsx
Visualization changes:
- Fix fetching external resource after selected from the visualization
- Wrap node title to div. This fixes issue YTI-4165
- Add origin to all edges, so the correct resource will be selected when clicking edge, even if there are corners between source and target
- Fix calculating starting point of the association edge. Change multiplier to 37.25 because borders don't increase the height of the node 2px but 1.25px. Set also height for node title, so it will be the same in both edit and view mode (in edit mode there is a button in top right corner, which increases the height of the element)
Other fixes
- Adjust codelist text margin and open link to new tab
=> YTI-4164 visualization ext references

datamodel-ui/src/modules/model/index.tsx
Previously, if the model page had a "new" query parameter, the module would use router to replace the url to not include it.
This breaks things, since new models are drafts, but urls without "new" or "draft" are considered non-drafts.
To fix this, the url replacement still remains, but now changes the "new" parameter to "draft".
=> YTI-4211 fix redirection after model creation

datamodel-ui/src/common/components/class/class.slice.tsx, datamodel-ui/src/common/interfaces/external-class.interface.ts, datamodel-ui/src/modules/class-view/application-profile-flow.tsx, datamodel-ui/src/modules/resource-picker-modal/index.tsx, datamodel-ui/src/modules/resource-picker-modal/util.tsx, datamodel-ui/src/store/tag-invalidator-middleware.ts
- Use `getExternalClass` endpoint if selected class is not Interoperability platform class
- Map external resource data as a `SimpleResource`
- Fixed tag invalidation when creating node shape. Also attribute and association lists must be invalidated because new properties might be created during creating new node shape.
=> YTI-4210 Handle external resources' properties

datamodel-ui/styles/globals.scss, terminology-ui/styles/globals.scss
This is fixed in suomifi-ui-components 14.0.1, but for now we'll just add a quick workaround.
=> Workaround for broken expanders on Chrome 129+ and Edge 129+

datamodel-ui/src/modules/resource/index.tsx
Browsing to an attribute/association would store the modelId in the "active" state, which would then be be considered the current modelId when creating a new attribute/association.
This means saving the new attribute/association was being done to whatever modelId was previously set in state.
This fix will reset the active state when browsing to the attribute/association create form, and the resource should now be saved to the proper datamodel.
=> YTI-3863 fix for resource being saved to a wrong datamodel

datamodel-ui/src/modules/class-view/resource-info.tsx
Resources picked from another model could not be removed. This fix will remove the check that disabled the dropdown, so "Remove" options should now appear.
Edit option should still remain disabled, since you can't edit resources of another model.
=> YTI-4215 fix removing resources picked from another model

terminology-ui/src/modules/new-terminology/info-manual.tsx
In the PR https://github.com/VRK-YTI/yti-ui/pull/741, properties of the `Prefix` component were changed. Apply those changes also to terminology UI.
=> fix prefix component properties

datamodel-ui/src/common/components/class/utils.ts, datamodel-ui/src/modules/class-form/index.tsx
Fixes for setting target class for node shape
- use versionIRI in properties if available (currently uses always draft version IRI)
- add external id, to indicate that we are adding reference to external resource
=> YTI-4235 Node shape's target class

datamodel-ui/public/locales/en/admin.json, datamodel-ui/public/locales/fi/admin.json, datamodel-ui/public/locales/sv/admin.json, datamodel-ui/src/common/components/model/model.slice.tsx, datamodel-ui/src/modules/delete-modal/index.tsx, datamodel-ui/src/modules/model/model-info-view.tsx
Allow deleting versioned data models for admin users. 
Deleting is denied, if status is `retired` or `superseded` and there are references to the model being deleted.
Otherwise, the list of referrer models is shown but delete button is enabled
For data models with status `valid`, delete option is not visible in the action menu.
=> YTI-4250 Delete versioned models

terminology-ui/public/locales/en/common.json, terminology-ui/public/locales/fi/common.json, terminology-ui/public/locales/sv/common.json, terminology-ui/src/common/components/as-file-modal/as-file-modal.styles.tsx, terminology-ui/src/common/components/as-file-modal/index.tsx, terminology-ui/src/common/components/info-dropdown/info-expander.test.tsx, terminology-ui/src/common/components/info-dropdown/info-expander.tsx, terminology-ui/src/pages/api/getTerminologyAsFile.ts
Add modal for selecting file format (json-ld, rdf or turtle) for export. Modal styles copied from datamodel application. In terminology, it's only possible to download file (no viewing in browser like in datamodel app).
=> YTI-4289 terminology export

terminology-ui/src/modules/own-information/subscription-block.tsx
Use resource's URI, e.g. https://iri.suomi.fi/terminology/test/, as an href value.
=> YTI-4291 Fix subscription links

terminology-ui/src/modules/vocabulary/index.tsx
This change should properly show the max page number at the bottom, e.g. `1/5`.
=> small fix for concept collections pagination

datamodel-ui/src/common/components/model/model.slice.tsx
This should fix an issue where attempting to create a new draft model would fail after having removed the previous draft.
YTI-4307
=> add cache invalidation tag for model slice

common-ui/components/form/language-selector.tsx, datamodel-ui/src/modules/documentation/index.tsx
Previous fix (#772) was done in the wrong place, this should be correct.
=> correctly increase max length for documentation textarea

terminology-ui/src/modules/vocabulary/index.tsx
Since pagination isn't supported by the backend, let's disable it for now.
This could be properly implemented later in frontend or backend.
=> disable unsupported pagination for collections
